### ISSUE TITLE
Animates in wrong direction for top / bottom

### ISSUE THREAD

**Issue by krebera** [exyte/PopupView#1]
Currently, when I go for a toast or a float, if I pass .top, it animates from the top bot goes all the way to the bottom. If I pass in .bottom, it animates from the bottom but goes all the way to the top

**Comment by f3dm76** [comment]
Hello @krebera , sorry for the wait. Does this still happen for you? Could you please provide some code or a small project archive so we can reproduce?

**Comment by f3dm76** [comment]
Hey @krebera, it's been a while, so I'm assuming everything is alright now, please let me now if you still have trouble with animation
