### ISSUE TITLE
background with visual effect blur

### ISSUE THREAD

**Issue by antonioreyna** [exyte/PopupView#101]
how can i set the background with a visual effect blur instead of a color, maybe it could be good instead of having the customize backgroundcolor, to just background and accept that View.

**Comment by f3dm76** [comment]
Hey @antonioreyna, sorry for the late response, but I'm happy to say that I added custom background builder as you asked. You are most welcome to check out version 2.2.2, have a wonderful day!

**Comment by antonioreyna** [comment]
awesome! let me try it thank you so much .
