### ISSUE TITLE
Usage with UIKit

### ISSUE THREAD

**Issue by zwirne** [exyte/PopupView#102]
Hi there,

I'd love to use your lib in my current project. Is there any way to use it with UIKit as well?

thank you for your amazing work!
zwirne

**Comment by f3dm76** [comment]
Hello @zwirne, thank you for your kind words, but I'd suggest you use a UIKit native solution for UIKit project, like this one https://github.com/huri000/SwiftEntryKit. If you still prefer using this library please search for something like https://blog.logrocket.com/how-add-swiftui-uikit-project/. Have a nice day
