### ISSUE TITLE
error on macOS: is only available on macOS 10.15 or newer

### ISSUE THREAD

**Issue by jiachen0814** [exyte/PopupView#103]
Worked fine on iOS but nor working on macOS

![Screen Shot 2023-03-20 at 7 41 53 PM](https://user-images.githubusercontent.com/69319792/226489058-f1cfff70-bfc0-40bc-8725-e40fcb42dc58.png)

**Comment by f3dm76** [comment]
Hey @jiachen0814, unfortunately we dropped macOS support, have a nice day

**Comment by f3dm76** [comment]
Hey @jiachen0814, I'm happy to let you know, I restored macOS and tvOS, please give version 2.3.0 a try. Have great day!
