### ISSUE TITLE
Popup not displayed when initial binding value is to show the popup

### ISSUE THREAD

**Issue by adusak** [exyte/PopupView#105]
Hello, I encountered (what I consider) an issue. When the initial biding controlling whether the popup should be shown is true the popup is not displayed.

Here is the minial reproduction code:

```
struct ContentView: View {
    @State var showingPopup = true
    
    var body: some View {
        VStack {
            Button("popmeup") {
                showingPopup = true
            }
        }.popup(isPresented: $showingPopup) {
            Text("The popup")
                .frame(width: 200, height: 60)
                .background(Color(red: 0.85, green: 0.8, blue: 0.95))
                .cornerRadius(30.0)
        } customize: {
            $0.closeOnTap(true)
        }
        
    }
}
```
What are your thoughts on how this should behave?
I believe that is some earlier version this worked the way I would expect.

Thank you!

**Comment by f3dm76** [comment]
Hey @adusak, could you please try version 2.3.0? I launched your example and popup is displayed (xcode 14.3, ios 16.4). Please feel free to re-open if you still see this issue, have a great day!

**Comment by adusak** [comment]
Sorry that I did not close the issue earlier, yes the new version works thank you very much 👍
