### ISSUE TITLE
 Popup view frame is not centered when device orientation is horizontal

### ISSUE THREAD

**Issue by nazar-velkakayev** [exyte/PopupView#110]
When running the example project in the PopupView library and turning the device horizontally, the popup view's frame is not centered on the screen

![Simulator Screen Shot - iPhone 11 Pro - 2023-05-04 at 16 48 39](https://user-images.githubusercontent.com/89843408/236196347-4f2a977d-aa44-46bf-ba24-58b55bc63dd2.png)

![Simulator Screen Shot - iPhone 11 Pro - 2023-05-04 at 16 48 43](https://user-images.githubusercontent.com/89843408/236196483-ffbf1400-7157-48a1-a9a1-f38499c5c462.png)

**Comment by f3dm76** [comment]
Hey @nazar-velkakayev, thanks for bringing this to my attention. Please check out version 2.3.1, should be fixed there. Please feel free to reopen if the issue persists, and be sure to have a marvellous day!

**Comment by nazar-velkakayev** [comment]
Hi @f3dm76 . Same problem with this type popup:

`        .popup(isPresented: $present) {
            Rectangle()
                .fill(.red)
                .frame(height: 200)

        } customize: {
            $0
                .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                .position(.bottom)
                .closeOnTapOutside(true)
                .backgroundColor(.black.opacity(0.4))
        }`

**Comment by f3dm76** [comment]
Hey @nazar-velkakayev, could you please try version 2.5.1? Please do let me know if you notice anything else, have a great day!
