### ISSUE TITLE
will add support popup from left or right and animated horizontal?

### ISSUE THREAD

**Issue by nicknull** [exyte/PopupView#112]
will add support popup from left or right and animated horizontal?

**Comment by nicknull** [comment]
for apple tv

**Comment by f3dm76** [comment]
Hey @nicknull, please check out version 2.4.0, I added the new appearFrom parameter which controls the animation direction. If not specified, it will behave as before. Have a nice day

**Comment by nicknull** [comment]
hey @f3dm76 thanks for your reply,  I'll try it
