### ISSUE TITLE
Bug in iPadOS 15

### ISSUE THREAD

**Issue by BredBurr** [exyte/PopupView#115]
Hey guys, just want to tell you that you have developed the best Popup library ever, thank you!

I've spotted a bug with iPadOS 15.
At first, I thought you dropped iOS15 support, but It seems like you still support iOS14, so:

If you create a popup with Navigation View like a so:
`struct AboutPopupView: View {
    @Binding var isPresented: Bool
    
    let longText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque urna turpis, luctus vitae vulputate et, aliquam sit amet magna. Ut rutrum odio libero, in laoreet mi placerat quis. Quisque ullamcorper lorem sit amet lacinia molestie. Mauris orci turpis, laoreet sed lacus et, porttitor tristique sapien. Sed placerat nec mauris ut suscipit. Integer eu felis tempor, malesuada ex id, tincidunt tellus. Donec at lacus ex. Praesent non sapien congue, maximus augue aliquam, accumsan nibh. Nullam quis consequat lacus, at vulputate quam. Suspendisse semper leo quis venenatis bibendum. Quisque gravida viverra ligula, eget ultricies ex maximus non. Nulla massa neque, auctor eu scelerisque sed, sollicitudin nec mauris. Aenean accumsan commodo nibh, et congue leo efficitur non. Quisque molestie est vel commodo maximus. Ut ac tempor ex, malesuada pellentesque massa. Phasellus rutrum urna est, commodo dapibus lacus tristique sed. Vestibulum dictum ac nisl non commodo. Aliquam ac efficitur lectus, at eleifend lectus. Mauris mollis velit orci, at commodo dolor pretium eu. Sed tristique id nunc id vulputate. Aliquam cursus volutpat nisi eu ornare. Integer condimentum auctor nibh, varius efficitur leo eleifend et. Donec euismod, leo in hendrerit eleifend, lorem dolor vulputate dui, sed sagittis lacus quam iaculis felis. Aenean accumsan commodo nibh, et congue leo efficitur non. Quisque molestie est vel commodo maximus. Ut ac tempor ex, malesuada pellentesque massa. Phasellus rutrum urna est, commodo dapibus lacus tristique sed. Vestibulum dictum ac nisl non commodo. Aliquam ac efficitur lectus, at eleifend lectus. Mauris mollis velit orci, at commodo dolor pretium eu. Sed tristique id nunc id vulputate. Aliquam cursus volutpat nisi eu ornare. Integer condimentum auctor nibh, varius efficitur leo eleifend et. Donec euismod, leo in hendrerit eleifend, lorem dolor vulputate dui, sed sagittis lacus quam iaculis felis."
    
    var body: some View {
        NavigationView {
            Form {
                Section {
                    Text(longText)
                }
            }
            .navigationBarTitleDisplayMode(.inline)
            .navigationTitle("About")
            .toolbar {
                ToolbarItemGroup(placement: .primaryAction) {
                    Button("Done") {
                        isPresented = false
                    }
                }
            }
        }
        .navigationViewStyle(.stack)
        .frame(width: 500, height: 500)
        .cornerRadius(30)
        .shadow(color: .black.opacity(0.2), radius: 15, x: 0, y: 0)
    }
}`

Open that popup in the iPadOS 15 simulator, tap the "Done" button - it closes - good!
Now open it again and try to scroll the long text inside the popup and then tap "Done" - it works 50/50 sometimes it closes the popup, and sometimes the "Done" button becomes unresponsive. 
This bug appeared in version 2.3.0. Version 2.2.2 works great on iPadOS 15.

Just wanted you to know.
Thanks again for your work and your time!

**Comment by f3dm76** [comment]
Hey @BredBurr, thank you so much for your kind words. Unfortunately I couldn't reproduce the issue neither on 2.3.0, nor on current master. But I've seen a similar issue (https://github.com/exyte/PopupView/issues/96). It's about NavigationView and cornerRadius, seems to be a SwiftU's bug:

https://developer.apple.com/forums/thread/118963?page=2#:~:text=.cornerRadius()%20is%20applied%20to%20the%20VStack%2C%20the%20Stepper()%20no%20longer%20works%20when%20tapped.%20Remove%20.cornerRadius()%20and%20everything%20works%20as%20expected.

https://www.hackingwithswift.com/forums/swiftui/transition-cornerradius-breaks-tap/12190

So you may try removing cornerRadius. Please let me know if it helps. Have a wonderful day!

**Comment by BredBurr** [comment]
Seems like it. You can't even have .cornerRadius(0) as it still brings the SwiftUI bug.

Thank you for the quick response!
