### ISSUE TITLE
white space at navigation bar in iOS 15

### ISSUE THREAD

**Issue by hapton** [exyte/PopupView#119]
self.popup(item: item, itemView: itemView, customize: {
            $0.type (.toast)
              .position(.bottom)
              .dragToDismiss(true)
              .isOpaque(true)
              .closeOnTap(false)
              .backgroundColor(.black.opacity(0.5))
        })

In ios 15 ,it have a white space at top. Ios 16 is ok.
<img width="303" alt="IMG_556D5D4AA499-1_jpeg" src="https://github.com/exyte/PopupView/assets/1235170/fbddae8a-5c75-4569-8ce8-4e8a26f0b0e9">

**Comment by f3dm76** [comment]
Hey @hapton, I launched your code, here is the result:
![simulator_screenshot_0AE3A663-4DC0-4D8A-A072-83D1DB74D20E](https://github.com/exyte/PopupView/assets/9447630/f7491736-1cfb-4bea-8da2-7ad30facf480)
Looks ok. Please provide your full compilable code reproducing the issue, device/sim model you are using and xcode version. Have a nice day

**Comment by f3dm76** [comment]
It's been a while, so I'll close this one for now. Please feel free to reopen if you are still having the issue. Please be sure to attach minimal compilable reproducible example. Have a nice day!
