### ISSUE TITLE
I would like to view the popups the same way as before version 2

### ISSUE THREAD

**Issue by tichise** [exyte/PopupView#121]
I would like to show the popup as it was in version 1, but with the popup the menu expands as if it is pushing out of the screen. What am I doing wrong?

https://github.com/exyte/PopupView/assets/43707/114965d4-aa2b-4b89-92b3-7532c864ec92

**Comment by f3dm76** [comment]
Hey @tichise, sorry I didn't get the problem, could you please explain more? What did you expect, and what should I see on this video?

**Comment by tichise** [comment]
I have an additional comment.

**Comment by tichise** [comment]
This one has resolved itself.
https://github.com/exyte/PopupView#show-over-navbar
