### ISSUE TITLE
When the app is in the stage manager and the width is very small on iPad OS, popup cannot be displayed

### ISSUE THREAD

**Issue by paulpaulzhang** [exyte/PopupView#124]
``` swift

.popup(isPresented: $showSendBox) {
                Text("test")
} customize: {
    $0.backgroundColor(.black.opacity(0.3))
        .closeOnTapOutside(true)
}
```

**Comment by f3dm76** [comment]
@paulpaulzhang But how would you like the popup to be displayed if the width is too small? Maybe I didn't get it right, could you please attach a picture?

**Comment by paulpaulzhang** [comment]
> @paulpaulzhang But how would you like the popup to be displayed if the width is too small? Maybe I didn't get it right, could you please attach a picture?

like this

**Comment by paulpaulzhang** [comment]
sorry, I accidentally mistakenly clicked!
this is image
![IMG_0326](https://github.com/exyte/PopupView/assets/40710267/62f60139-8984-4311-bc32-6c2d1a9b9086)

**Comment by f3dm76** [comment]
I made an adjustment - for non opaque popups I use the size of presenting window - not the screen size. I think it should fix your problem, could you please try version 2.5.3?

**Comment by paulpaulzhang** [comment]
> I made an adjustment - for non opaque popups I use the size of presenting window - not the screen size. I think it should fix your problem, could you please try version 2.5.3?

Thank you for responding so quickly! but after testing, I found that there were still issues:
1. When the keyboard pops up in non opaque mode, the view is blocked by the keyboard because it does not move up
2. When creating a popupview using the following code, the pop-up view will first appear in the top left corner of the screen (for a moment), and then appear from the bottom up, this phenomenon may not occur every time.
``` swift
$0.popup(isPresented: $showSendBox) {
    Text("test")
        .frame(width: 300, height: 200)
        .background(.black)
} customize: {
    $0
   .closeOnTapOutside(true)
        .closeOnTap(false)
        .dragToDismiss(false)
        .backgroundColor(.black.opacity(0.25))
        .animation(.linear(duration: 0.2))
        .position(.bottom)
        .type(.toast)
}
```

Also, can you use presenting window to calculate size in opaque mode?

**Comment by f3dm76** [comment]
The point of opaque mode is to be on top of navbar (it is unobviously super complicated to achieve for some reason). And if I use presenting window size it will not account for navbar size. So this I can not do. But why would you need opaque popup if not to be independent from presenting view at all? I will look into issues you mentioned as soon as I can. Have a great day!

**Comment by paulpaulzhang** [comment]
> The point of opaque mode is to be on top of navbar (it is unobviously super complicated to achieve for some reason). And if I use presenting window size it will not account for navbar size. So this I can not do. But why would you need opaque popup if not to be independent from presenting view at all? I will look into issues you mentioned as soon as I can. Have a great day!

Thanks! I need opaque mode just because I need use closeOnTapOutside option

**Comment by f3dm76** [comment]
Hey @paulpaulzhang, please check out version 2.5.6, both issues should be fixed there. Have a great day!
