### ISSUE TITLE
isOpaque not working in some instance

### ISSUE THREAD

**Issue by nhjariwala** [exyte/PopupView#125]
Thanks a lot for a great library.

I'm having issue on `isOpaque` its not working on some iOS version and iPad model like below 
`iPad Air 2	15.7.6`
`iPad Air 2	15.7.6`
`iPad Air 2	15.7.6`
`iPad 8th Gen	16.5`
`iPad 9th Gen	16.5`

when `isOpaque(true)` set it will not show view

I'm showing view using below code 

```
.popup(isPresented: $isOpen2) {
            DemoPopupView2(isOpen2: $isOpen2)
        } customize: {
            $0
                .type(.default)
                .closeOnTapOutside(false)
                .closeOnTap(false)
                .dragToDismiss(false)
                .backgroundColor(Color.black.opacity(0.4))
                .isOpaque(true)
        }
```
Its works fine in some device but not working on above device. I have huge code thus can't replicate the same or share the code but its definitely something thats stopping view to present.

Any help would be highly appreciated . Thanks

**Comment by f3dm76** [comment]
Hey @nhjariwala, are you using a simulator? I don't see 16.5 or 15.7 iOS simulators in xcode 14.3, 14.3.1 or xcode 15 beta, could you please point me to how I can get to run the example on one? Or maybe you can help me diagnose the problem from your end. Maybe these versions will be available in the next xcode release... Have a great day

**Comment by f3dm76** [comment]
@nhjariwala, We've launched your code on iPad Air 5th gen iPadOS 16.5.1, here is the video, looks ok

https://github.com/exyte/PopupView/assets/9447630/66481da0-7801-462c-9525-cbcba06db601

Are you sure it is not something in your code? I don't know what's in DemoPopupView2, but does it also happen for something simple like `Color.red`?

**Comment by f3dm76** [comment]
It's been a while, so I'll close this one for now. Please feel free to reopen if you are still having the issue. Have a nice day!
