### ISSUE TITLE
is that any possible way to use this library on UIViewController instead of swiftUI view ?

### ISSUE THREAD

**Issue by chetandobariya** [exyte/PopupView#126]
I have one situation that I would like to show popup on currently presented screen in app.

to get currently presented screen using UIKit is super easy and fast and than we can show alert. 

But this library only works with SwiftUI Views.   If we can use this library on UIKit than would be awesome and very much blessed!

**Comment by f3dm76** [comment]
Please refer to this issue
https://github.com/exyte/PopupView/issues/102
Have a nice day
