### ISSUE TITLE
2.5 broke .dragToDismiss for middle popups

### ISSUE THREAD

**Issue by BredBurr** [exyte/PopupView#128]
Hi guys, thanks so much for this great PopupView!
I think you broke .dragToDismiss for the middle popups in >= 2.5.0. 

Try it yourself, in the PopupExample -> ContentView, add `.dragToDismiss(true)` on line ~239 and try to drag it down to dismiss... it doesn't 😄

Happy to help you!

**Comment by f3dm76** [comment]
Hey @BredBurr, thank you so much for bringing this to my attention! Please check out version 2.5.5 and have a wonderful day!

**Comment by BredBurr** [comment]
And thank you! It works like a charm!
