### ISSUE TITLE
Minor issue on .dragToDismiss for middle popups on v2.5

### ISSUE THREAD

**Issue by BredBurr** [exyte/PopupView#129]
Hello again! Another minor issue I've found is when you try to drag the middle popup up. Not down to dismiss it, but up. 
It will "jump" up and then return to its middle position. 

You should have .dragToDismiss = true. This behavior is only seen on >v2.5. Previously, when you dragged the popup up nothing happened (as I believe is the correct behavior).

Thanks again for that wonderful library!

**Comment by f3dm76** [comment]
Hey @BredBurr, thanks for letting me know! Please give version 2.5.7 a go, have a marvellous day!
