### ISSUE TITLE
I want to center my subview logic on top of TabView. 

### ISSUE THREAD

**Issue by wscqs** [exyte/PopupView#133]
I want to center my subview logic on top of TabView. The framework is not supported yet. Support for example: https://github.com/AndreaMiotto/PartialSheet rootView. AttachPartialSheetToRoot () to deal with?

**Comment by f3dm76** [comment]
Hey @wscqs, to be honest I didn't get your question. Please try to explain more.

If you want a partial sheet like in the attached repo, please refer to `// MARK: - Designed action sheets` (line 266 ContentView.swift) section of the example project. Have a nice day

**Comment by wscqs** [comment]
> Hey @wscqs, to be honest I didn't get your question. Please try to explain more.
> 
> If you want a partial sheet like in the attached repo, please refer to `// MARK: - Designed action sheets` (line 266 ContentView.swift) section of the example project. Have a nice day

Sorry, your library can implement a middle mask effect on Tabview. I'll close the question right away.
