### ISSUE TITLE
The position of popup view in default mode on macOS is incorrect

### ISSUE THREAD

**Issue by WalterZou** [exyte/PopupView#137]
I am using the Sheet (type:.default) mode on macOS, and the window is not positioned at the bottom as expected, but at a strange location. Below is a screenshot:
![image](https://github.com/exyte/PopupView/assets/3727208/be0a18b5-a6a2-4b2b-9c61-406067be7845)

This is the desired style (achieved by manually dragging to this position):
![image](https://github.com/exyte/PopupView/assets/3727208/efffcdce-8ebb-4ef9-963d-ff50e2342ce0)

This is my code:
```
 .popup(isPresented: sheetIsPresented()) {
              SomeView()
            } customize: {
                $0
                    .position(.bottom)
                    .dragToDismiss(true)
                    .animation(.smooth)
                    .closeOnTapOutside(true)
                    .isOpaque(true)
            }
}
```

**Comment by f3dm76** [comment]
Hey @WalterZou, I've launched your code on mac, xcode 14.3.1, here is a gif and full compilable code:
https://github.com/exyte/PopupView/assets/9447630/05492634-4a3c-4b86-8695-d2fe057962d9

```
struct ContentView: View {

    @State var isPresented1 = false

    var body: some View {
        VStack {
            Button("First") {
                isPresented1 = true
            }
        }
        .popup(isPresented: $isPresented1) {
            Color.red.frame(width: 100, height: 100)
          } customize: {
              $0
                  .position(.bottom)
                  .dragToDismiss(true)
                  //.animation(.smooth)
                  .closeOnTapOutside(true)
                  .isOpaque(true)
          }
    }
}
```
Please provide full minimal compilable example and make sure the issue reproduces on this minimal example. Have a nice day

**Comment by WalterZou** [comment]
I misunderstood the usage, it should be used like this to avoid this problem.
```
struct ContentView: View {

    @State var isPresented1 = false

    var body: some View {
        VStack {
            Button("First") {
                isPresented1 = true
            }
        }
        .popup(isPresented: $isPresented1) {
            Color.red.frame(width: 100, height: 100)
          } customize: {
              $0
                  .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                  .position(.bottom)
                  .dragToDismiss(true)
                  //.animation(.smooth)
                  .closeOnTapOutside(true)
                  .isOpaque(true)
          }
    }
}
```
I originally thought that `type` with `.default` meant "Sheet" mode, but it should actually be `.type(.floater(verticalPadding: 0, useSafeAreaInset: false))`. Thank you for your response. I have closed this issue and related PR.
