### ISSUE TITLE
Popup is not centered in macCatalyst

### ISSUE THREAD

**Issue by harthorst** [exyte/PopupView#138]
The popup does not appear centered under some circumstances.

This works fine:
`.popup(isPresented: $iapModel.isShowPaymentPopup) {
                IAPPopupView()
            } customize: {
                $0
            }`

This does not show the popup in the center of the window:
`.popup(isPresented: $iapModel.isShowPaymentPopup) {
                IAPPopupView()
            } customize: {
                $0.closeOnTapOutside(true)
            }`

I get the same result when using `.isOpaque(rue)`

My app is based on UIKit hosting SwiftUI. 

MacOS: 13.4.1
XCode: 14.3.1
PopupView 2.6.0

**Comment by f3dm76** [comment]
Hey @harthorst, sorry, but we do not support mac catalyst. Also, if you are running UIKit, please consider using a UIKit native solution for popups. Have a nice day
