### ISSUE TITLE
Is there any way to disable 'appearFrom' animation?

### ISSUE THREAD

**Issue by Robotxm** [exyte/PopupView#140]
I want to make a popup view like `DialogFragment` in Android, but it seems that I cannot disable `appearFrom` animation. Is there any way to make it?

**Comment by f3dm76** [comment]
Hey @Robotxm, if I understand you correctly, you can just show your desired view on top of whatever you have using ZStack, and you don't need this library

**Comment by f3dm76** [comment]
Closing this one for now, please feel free to reopen with more details
