### ISSUE TITLE
Offset while keyBoard showed

### ISSUE THREAD

**Issue by lchxair** [exyte/PopupView#141]
i got this pop from bottom position,  it last for 3 second then atuo hide.
 But  showing a keyboard meanwhile, will cause the pop move up to the middle of screen. 
The normal case:
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-18 at 09 16 37](https://github.com/exyte/PopupView/assets/70889748/718e0c30-c67a-4701-9641-c6f74cbdb364)

 The keyboard case:
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-18 at 09 17 02](https://github.com/exyte/PopupView/assets/70889748/7ea636b1-b0fd-4d51-b800-91e13c631a84)

Is there anyway to keep the pop at bottom? Or hide it while keyboard showing?

I'm not sure if this is a stupid question. Thanks.

**Comment by victorazzo** [comment]
This is likely the issue "Keyboard handling for popups #81" again... I still have the issue with the popup jumping up too far when the keyboard shows.

**Comment by f3dm76** [comment]
Hey @lchxair, please check out version 2.6.1 - I've added `useKeyboardSafeArea` parameter, and by default keyboard avoidance shouldn't be forced by Popup library. If the issue persists, please use SwiftUI's `.ignoresSafeArea(.keyboard)`

**Comment by lchxair** [comment]
> Hey @lchxair, please check out version 2.6.1 - I've added `useKeyboardSafeArea` parameter, and by default keyboard avoidance shouldn't be forced by Popup library. If the issue persists, please use SwiftUI's `.ignoresSafeArea(.keyboard)`

.ignoresSafeArea(.keyboard)  did the trick.Thanks
