### ISSUE TITLE
How can i make the popup dismiss if an inside scrollview was already scrolled to the top

### ISSUE THREAD

**Issue by ajunjunandtmac** [exyte/PopupView#142]
Any suggestion when you have time
I will be really appreciated.

**Comment by f3dm76** [comment]
Hey @ajunjunandtmac, did you try using `dragToDismiss`?

**Comment by ajunjunandtmac** [comment]
> Hey @ajunjunandtmac, did you try using `dragToDismiss`?

yes .dragToDismiss(true)  this modifier i have already added.
I thinks the problem was that the scroll gesture blocked the drag gesture

**Comment by f3dm76** [comment]
There is an example of such an arrangement in example project - sheets section, last example. If you are still having trouble, please provide full minimal compilable example and make sure the issue reproduces on this minimal example. Have a nice day

**Comment by f3dm76** [comment]
If you mean you want to actually replace the standard overscroll animation of a ScrollView with dismissal of a popup, there is no way for me to tell if there is a ScrollView inside the content you provide, since it's just a view builder inside of my library

**Comment by ajunjunandtmac** [comment]
> There is an example of such an arrangement in example project - sheets section, last example. If you are still having trouble, please provide full minimal compilable example and make sure the issue reproduces on this minimal example. Have a nice day

thanks， i will check it later.
