### ISSUE TITLE
Hello, why opaqueBackgound is determined by closeOnTapOutside 

### ISSUE THREAD

**Issue by ajunjunandtmac** [exyte/PopupView#143]
`var opaqueBackground: Bool {
        isOpaque || closeOnTapOutside
    }
`
if i don't want to show popup via fullScreenCover modifier,  just show inside a view, meanwhile i need to keep the closeOnTapOutside function, how can i do that?
```
@ViewBuilder
public func main(content: Content) -> some View {
    if opaqueBackground {
#if os(iOS)
        content.transparentNonAnimatingFullScreenCover(isPresented: $showSheet) {
            constructPopup()
        }
#else
        ZStack {
            content
            constructPopup()
        }
#endif
    } else {
        ZStack {
            content
            constructPopup()
        }
    }
}
```
Thanks for you help

**Comment by f3dm76** [comment]
Hey @ajunjunandtmac, I'm sure I had a reason, but I do not remember it, so I removed this for now. Please do keep an eye on possible problems that might have caused, have a nice day

**Comment by ajunjunandtmac** [comment]
> 
okay，i will try the new version and report to you, thanks very much.

**Comment by ajunjunandtmac** [comment]
Nothing wrong after my simple test
And also if i make the popup only displayed inside the current view, can it solve the problem that the system only allow one pop-up in the same time? is it a better way to show the popup?

**Comment by f3dm76** [comment]
I didn't really get your question, sorry. Opaque popups use fullScreenCover, it doesn't matter which view you use it on, system won't allow it. Non opaque - you can show as many as you want on whatever view you want. Nothing is better they are just different, opaque can be shown above navbar, and non-opaque can not.
