### ISSUE TITLE
issues with iOS 16.6

### ISSUE THREAD

**Issue by adesun2k** [exyte/PopupView#145]
Just a heads up.. this seems to have broken since 2.6.3
This library misbehave on iOS 15.7.3 iOS 16.6
It doesn't close on $isPresenter is toggled false.
It doesn't respond to close on tap outside.

Please we are using your library in production please ensure you test on real device properly before pushing new update. It's becoming a sort of embarrassment to us in front of users please

**Comment by cibetik** [comment]
Moving to 2.6.1 helps.

**Comment by f3dm76** [comment]
Hey @adesun2k, please check out version 2.7.0, issue should be fixed there. Have a nice day

**Comment by adesun2k** [comment]
> Hey @adesun2k, please check out version 2.7.0, issue should be fixed there. Have a nice day

Thanks alot. God bless.

**Comment by adesun2k** [comment]
> Hey @adesun2k, please check out version 2.7.0, issue should be fixed there. Have a nice day

[!] CocoaPods could not find compatible versions for pod "ExytePopupView":
  In Podfile:
    ExytePopupView (= 2.7.0)

None of your spec sources contain a spec satisfying the dependency: `ExytePopupView (= 2.7.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
<img width="569" alt="Screenshot 2023-09-23 at 08 45 18" src="https://github.com/exyte/PopupView/assets/57893099/e8a686af-7f19-47c3-a170-b7f4754c8f8e">
