### ISSUE TITLE
Binding var does not close out view

### ISSUE THREAD

**Issue by Holychris56** [exyte/PopupView#146]
Very interesting results with iOS 17. I updated xcode to support iOS 17, and now the library seems broken. I tried to close out the view, by setting the state var popup(isPresented: $isUserPosting) to false, and it tries to close, but never actually closes. It comes back up.

Has this been tested with iOS 17?

**Comment by Holychris56** [comment]
Interesting, Version 2.6.1 works. Looks like I updated to the latest version, and it broke it. Went back to 2.6.1, and all is well

**Comment by f3dm76** [comment]
Hey @Holychris56, sorry for the delay, please check out version 2.7.0, issue should be fixed there. Have a great day!
