### ISSUE TITLE
isOpaque does not move view with keyboard

### ISSUE THREAD

**Issue by Holychris56** [exyte/PopupView#147]
On iOS 17, having the isOpaque set to true does not allow the keyboard to move the view. The keyboard will block the view if it has isOpaque set to true on iOS 17.

**Comment by f3dm76** [comment]
Hey @Holychris56, there is a useKeyboardSafeArea parameter for bottom popups, also you might achieve what you want using system keyboard avoidance settings. If these options don't help, please provide your code, so I can reproduce your particular issue

**Comment by Holychris56** [comment]
Hey @f3dm76, ok looks good! However, the toolbars are now broken. Looks like my toolbar has disappeared lol. 

                .popup(isPresented: $isPresenting) {
                    TestView()
                        .preferredColorScheme(.dark)
                        .environment(\.colorScheme, .dark)
                    
                } customize: {
                    $0
                        .isOpaque(true)
                        .useKeyboardSafeArea(true)
                        .type(.toast)
                        .position(.bottom)
                        .backgroundColor(.black.opacity(0.4))
                        .closeOnTap(false)
                }


Struct TestView: View
{
var body: some View
{
       test()
        .toolbar
        {
            ToolbarItem(placement: .keyboard)
            {
                Button("Done")
                {

                }.foregroundColor(Color(UIColor.stockOrbitTeal))
                    .frame(maxWidth: .infinity, alignment: .trailing)
            }
        }
    }
}
}

**Comment by f3dm76** [comment]
Hey @Holychris56, this is an Apple bug with `fullScreenCover`. Opaque mode is implemented using `fullScreenCover` since it is the only way I could find to display over navbar. Please do let me know if there is another way. Here is the code demonstrating Apple's bug:

```
.fullScreenCover(isPresented: $isPresented) {
    TextField("Your name", text: $name)
        .padding()
        .background {
            RoundedRectangle(cornerRadius: 12)
                .stroke(.black)
        }
        .padding(EdgeInsets(top: 37, leading: 24, bottom: 40, trailing: 24))
        .background(Color.white.cornerRadius(20))
        .toolbar {
            ToolbarItem(placement: .keyboard) {
                Button("Done") { }
                .frame(maxWidth: .infinity, alignment: .trailing)
            }
        }
}
```
