### ISSUE TITLE
Sheet indicator not shown

### ISSUE THREAD

**Issue by phoenix-error** [exyte/PopupView#149]
Hey guys I am using your PopupView and it is great. But on my iOS 17 device I cannot get the Indicator of the sheet to be shown (so the user knows he can drag down). How can I fix this?

.popup(isPresented: $showPopup) {
            AddItemPopupView(isDisplayed: $showPopup)
                .shadow(color: .black.opacity(0.08), radius: 2, x: 0, y: 0)
                .shadow(color: .black.opacity(0.16), radius: 24, x: 0, y: 0)
                .padding(.top)
                .frame(height: 400)
                .clipShape(RoundedRectangle(cornerRadius: 12.0))
                
        } customize: {
            $0
                .type(.toast)
                .position(.bottom)
                .useKeyboardSafeArea(true)
                .closeOnTap(false)
                .closeOnTapOutside(true)
                .dragToDismiss(true)
                .backgroundColor(.black.opacity(0.4))
        }

**Comment by f3dm76** [comment]
Hey @phoenix-error, if I understood correctly, this small line indicator should be the part of your popup. Just add it and your content to a VStack. Please see .sheet section in the example project. Have a fantastic day!
