### ISSUE TITLE
Tap to dismiss doesn't cancel previously scheduled auto hide DispatchWorkItem

### ISSUE THREAD

**Issue by JLZ** [exyte/PopupView#15]
I've implemented a queue of toasts, using `PopupView` for presentation. The issue I'm running into is that when a toast is dismissed via tap and I present the next toast in queue, it gets auto-hidden early. It looks like this is the code with the bug.

```
if let autohideIn = autohideIn {
    dispatchWorkHolder.work?.cancel()
    dispatchWorkHolder.work = DispatchWorkItem(block: {
        self.isPresented = false
    })
    if isPresented, let work = dispatchWorkHolder.work {
        DispatchQueue.main.asyncAfter(deadline: .now() + autohideIn, execute: work)
    }
}
```

It seems that since `dispatchWorkHolder` is a class, it's `work` property is being passed by reference. Therefore, when I present a second toast, the `work` property is set to a new `DispatchWorkItem` that has not been cancelled. So at the time the previously scheduled `asyncAfter` executes, it is not a cancelled item.

**Comment by f3dm76** [comment]
Hey @JLZ , thank you for your feedback. Could you please try modifying PopupView's code like this:
`if self.closeOnTap {
        self.dispatchWorkHolder.work?.cancel()
        self.isPresented = false
    }`
If that doesn't fix your issue, please attach some code for me to reproduce your issue. If it does, I'll make new pod release with this change. Have a nice day!

**Comment by JLZ** [comment]
@f3dm76 good call. This fixed the issue. I posted a PR with the fix [here](https://github.com/exyte/PopupView/pull/16).

Thanks!

**Comment by f3dm76** [comment]
@JLZ All done, version 0.0.8, you are most welcome to check it out, have a nice day!
