### ISSUE TITLE
problem on dismissCallback

### ISSUE THREAD

**Issue by Begoodi** [exyte/PopupView#150]
Hi,

Apparently, the dismiss callback is executed once the popup id dismissed, il when it disappears completely.
I'm trying to play a sound when the popup dismiss, but in that case it's too late.
Is there a way to execute some code (play sound) just at the beginning of the dismiss animation ?

Thanks :)

**Comment by f3dm76** [comment]
Hey @Begoodi, how are you dismissing? Since, for example, if you change isPresented, you can play the sound in the same code. Or you can attach a simultaneous gesture if you use on tap I think. Have a great day

**Comment by Begoodi** [comment]
Hi, thanks for your answer :)
Yes I can manage the close sound by myself in some cases, as you say when I change isPresented, but if I use the option .closeOnTapOutside(true) I don't know how to do.

**Comment by f3dm76** [comment]
You can pass a custom backgroundView with the extra gesture

**Comment by Begoodi** [comment]
There is also the tap on the view itself.
But yes could be a workaround, but adding too much reduce the advantage to use a library.
Is there a chance it could be on a future update ?

**Comment by f3dm76** [comment]
Hey @Begoodi, I've added `willDismissCallback` parameter I think you can use, please check out version 2.8.0, have a nice day

**Comment by Begoodi** [comment]
Works perfectly, thanks. :)
