### ISSUE TITLE
[Xcode 14] Extra trailing closure passed in call on the latest 2.8.0 release 

### ISSUE THREAD

**Issue by jblanco-applaudostudios** [exyte/PopupView#152]
Hi, there seems to be a problem on line 509 of `PopupView.swift` that causes builds using Xcode 14 to fail due to the following reason:

```
SourcePackages/checkouts/PopupView/Source/PopupView.swift:509:43: extra trailing closure passed in call
} completion: {
```

This version works correctly when using Xcode 15. 
Rolling back to the previous 2.7.0 version fixes the issue. It seems that the `completion` closure is not working as expected on Xcode 14.

<img width="1108" alt="image" src="https://github.com/exyte/PopupView/assets/87678065/16349168-0a00-4ff8-8f1e-2bf00b76573b">

**Comment by f3dm76** [comment]
Hey @jblanco-applaudostudios, thank you for bringing this to our attention, could you please try version 2.8.1? Have a fantastic day!

**Comment by f3dm76** [comment]
Hey @tbarri, could you please try 2.8.2? I changed the version to 5.9 there

**Comment by f3dm76** [comment]
Thank you for making sure it works! ❤️
