### ISSUE TITLE
dismissCallback code still under .isOpaque(true) popup influence

### ISSUE THREAD

**Issue by victorazzo** [exyte/PopupView#159]
Issue is related to dismissCallback being called while the popup isOpaque(true) is still preventing any other alert to show in the screen. Expected outcome would be that the popup would be fully dismissed on the dismissCallback.

Here is a minimally functional example view showing the issue (including commented not desirable workaround of a DispatchQueue.main.asyncAfter):

`
import SwiftUI
import PopupView

struct MinimallyFunctionalExample: View {
    @State private var showEdit = false
    @State private var showDeleteAlert = false
    @State private var triggerDeleteAlert = false
    
    var body: some View {
        VStack {
            Button("Show Popup") {
                showEdit = true
            }
            .popup(isPresented: $showEdit) {
                VStack {
                    Text("Popup Content")
                    Button("Delete") {
                        triggerDeleteAlert = true
                        showEdit = false
                    }
                }
                .frame(width: 200, height: 100)
                .background(Color.gray)
            } customize: {
                $0.type(.floater())
                    .closeOnTapOutside(true)
                    .isOpaque(true)
                    .position(.bottom)
                    .animation(.spring())
                    .dismissCallback {
                        if triggerDeleteAlert {
                            triggerDeleteAlert = false
                            // Not desirable workaraound to avoid the issue:
                            // DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                                showDeleteAlert = true
                            //}
                        }
                    }
            }
            .alert(isPresented: $showDeleteAlert) {
                Alert(
                    title: Text("Delete Item"),
                    message: Text("Are you sure you want to delete this item?"),
                    primaryButton: .destructive(Text("Delete")) {
                        // Handle delete action
                    },
                    secondaryButton: .cancel()
                )
            }
        }
    }
}

`

Thank you!

**Comment by f3dm76** [comment]
Hey @victorazzo, isOpaque(true) uses fullscreenCover inside, so it works the same way. So if you can not use apple's fullscreenCover and alert simultaneously, same goes for opaque popup, and there is nothing that can be done. Have a great day!

**Comment by victorazzo** [comment]
Hi @f3dm76. Thanks for the quick feedback. We are on the same page about the fullscreenCover expected behavior vs alerts. Am I mistaken to assume that the popview should be entirely dismissed (fullscreenCover included) by the time the dismissCall code is executed? That is the issue, more specifically.

**Comment by f3dm76** [comment]
Ah, got it, sorry. I'll be sure to look into your issue as soon as I can, thank for reporting the issue!

**Comment by f3dm76** [comment]
@victorazzo, please check out version 2.8.3, should be fixed there, have a wonderful day!

**Comment by victorazzo** [comment]
@f3dm76 , issue solved! Awesome! Thank you and have a wonderful day.
