### ISSUE TITLE
Add the ability for a scrolling content

### ISSUE THREAD

**Issue by murad1981** [exyte/PopupView#161]
I suggest to add the option to scroll the pop up content if its text is larger than the view's height instead of truncating the text, as appears in the following screenshot:

![popup large content](https://github.com/exyte/PopupView/assets/1199045/74c242c5-0ac9-4a68-bf26-a480be6a14f6)

**Comment by f3dm76** [comment]
Hey @murad1981, the contents of your popup is entirely up to you, you can add a ScrollView if you'd like
