### ISSUE TITLE
Wrong frame when using isOpaque(true) on iPad with multi tasking

### ISSUE THREAD

**Issue by plu** [exyte/PopupView#162]
When you set `isOpaque(true)` and the app runs side-by-side with another app on iPad, the frame for the popup is not correct.

Tiny patch to reproduce:

```diff
diff --git a/PopupExample/PopupExample/ContentView.swift b/PopupExample/PopupExample/ContentView.swift
index 096eff9..21074fe 100644
--- a/PopupExample/PopupExample/ContentView.swift
+++ b/PopupExample/PopupExample/ContentView.swift
@@ -246,6 +246,7 @@ struct ContentView : View {
             } customize: {
                 $0
                     .closeOnTap(false)
+                    .isOpaque(true)
                     .backgroundColor(.black.opacity(0.4))
             }
 
```

Then launch the app on iPad, put another app side-by-side and open the `Middle` popup.

<img src="https://github.com/exyte/PopupView/assets/31597/bc5b5538-e1c4-4959-b16a-b408e436afcb" width=400>

**Comment by plu** [comment]
I have a potential fix, but I'd be super careful with merging that one. I'm not sure what it might be breaking, probably several other use cases :).

https://github.com/exyte/PopupView/assets/31597/e47776b6-e433-487c-a192-cbc33efcc975

**Comment by plu** [comment]
https://github.com/plu/PopupView/commit/3a93ddc773241ab02f169f9f09cde8add2c7190b

**Comment by NikosP** [comment]
@plu Your fix works for me, but unfortunately it breaks touching outside the popup to dismiss the popup in my case. Unfortunately I couldn't figure out why being a beginner with iOS development.

**Comment by f3dm76** [comment]
Hey guys @plu @NikosP, could you please check out version 2.10.2? The issue should be fixed there, have a great day!
