### ISSUE TITLE
will add support popup from center animated horizontal? 

### ISSUE THREAD

**Issue by pepenb** [exyte/PopupView#163]
appearFrom by default only animations from up and down left and right and not from the middle  I know  the position default is in the middle but I'd like to add a popup effect that starts in the middle and goes from small to large or an animation that goes in and out of the middle want to add the effect of implementing alert

**Comment by swilson** [comment]
I kludged something together here: https://github.com/swilson/PopupView/tree/center_popup.


https://github.com/exyte/PopupView/assets/2624622/f71586dc-3a8c-4305-a280-8391f1d5a587

**Comment by pikacode** [comment]
> appearFrom by default only animations from up and down left and right and not from the middle I know the position default is in the middle but I'd like to add a popup effect that starts in the middle and goes from small to large or an animation that goes in and out of the middle want to add the effect of implementing alert

Hi, I've created a plugin that can pop up from the center. Maybe this can help you:)
[https://github.com/pikacode/PopupUI](https://github.com/pikacode/PopupUI)

**Comment by SnowLukin** [comment]
@swilson Could you please give some examples of how to implement what you modified?

**Comment by swilson** [comment]
No haven't bothered looking into it.

**Comment by f3dm76** [comment]
@pepenb the animation you described sounds super custom, this library can only animate popup's position, not its size. Please just use simple SwiftUI animations on your view to achieve that
