### ISSUE TITLE
`dragToDismiss` when content is a scroll view

### ISSUE THREAD

**Issue by oscarvgg** [exyte/PopupView#164]
Is there any easy way to make drag to dismiss work when the content is a scroll view? By that, I mean that scrolling to a negative offset would drag the popup view.

**Comment by ZA74968** [comment]
Any updates about this? I'm looking for same feature - I need to make a bottom sheet dismissable when its content is scrollview. For I'm using native `sheet()` modifier but it is not a good solution for me

**Comment by f3dm76** [comment]
Hey guys, no, unfortunately this functionality is not implemented in this lib. We'll consider adding this when we have time. You are most welcome to commit a PR adding this to the lib. Have a great day!

**Comment by f3dm76** [comment]
Hey @oscarvgg @ZA74968, please check out version 2.9.0 - we added .scroll popup type, which can be dismissed with a single scroll motion - please check it out. Have a wonderful day!

**Comment by b95505017** [comment]
I tried `.scroll` type with `dragToDismiss`, but they seems conflict. When I try to scroll to the top, it will also trigger `dragToDismiss`.

**Comment by f3dm76** [comment]
Hey @b95505017, drag gesture is built into the .scroll type, if I remember correctly, try removing it, and just leave .scroll type. have a nice day
