### ISSUE TITLE
[Question] Does PopupView supports displaying floaters inside Views?

### ISSUE THREAD

**Issue by BredBurr** [exyte/PopupView#165]
Hi, this is a simple yes/no question, so you don't stress over the holidays 🤗
Many libraries typically display floaters appearing from outside the screen, and so does PopupView. But is it possible to show a floater that appears from within the screen, inside a View, say?
Just for example here is a drawing of a floater, that appeared below the Translator Views (forgive my drawing skills 🙈 ):

![Screenshot](https://github.com/exyte/PopupView/assets/124914915/1394da72-4c15-467f-b6ba-efd51884eb86)

Thanks for your fantastic work!
Wishing you happy holidays and all the best!

**Comment by f3dm76** [comment]
Hey @BredBurr sorry, no, we do not support that. This seems like a very custom use-case, so I don't think we'll implement that. Have a nice day
