### ISSUE TITLE
Swift Package Manager name too common

### ISSUE THREAD

**Issue by JLollback** [exyte/PopupView#166]
I'd absolutely love to use this package for an alert view, it's beautiful! However I already use a different SwiftPM also named PopupView, that I need (which meets my needs) and therefore can't use this one. Is there a way to have the package name changed to something like ExytePopupView (Similar to what had to happen with the MediaPicker package)? I do find this issue with the naming does happen often with generic and possibly common function names. Cheers!

**Comment by f3dm76** [comment]
Hey @JLollback, I think you can use module aliases far that https://kazaimazai.com/whats-new-in-swift-wwdc22/
I'm just afraid if I rename it now it'll create problems for many more people than MediaPicker's renaming...
Have a great day!
