### ISSUE TITLE
DispatchWorkItem is no longer cancelled on tap

### ISSUE THREAD

**Issue by JLZ** [exyte/PopupView#17]
The fix I applied [here](https://github.com/exyte/PopupView/pull/16/files) was removed in 0.9 and the same [issue](https://github.com/exyte/PopupView/issues/15) is occurring again.

**Comment by f3dm76** [comment]
Hey @JLZ, I'm so sorry about that, restored in 0.0.10, please try it out, and have a nice day!

**Comment by JLZ** [comment]
Thank you!
