### ISSUE TITLE
Focus removed when popup dismisses

### ISSUE THREAD

**Issue by benjamin-es-hall** [exyte/PopupView#170]
I have a use case where I show a floater style popup whilst a SwiftUI textfield is focuses (keyboard shown). I noticed when the toast auto hides (only case I've tested) it calls some code that dismisses the keyboard, resulting in focus being lost to my textfield. 

This seems like it isn't intended behaviour and if so not sure why. I found this [PR](https://github.com/exyte/PopupView/pull/153/commits/367c3b985723fb1e68e344b40dc142fd756bf868) introducing the change but couldn't find context as to why?

https://github.com/exyte/PopupView/blob/4e64eb67d4510c96f82efd9e34b8fa5b9b397791/Source/FullscreenPopup.swift#L240

**Comment by f3dm76** [comment]
Hey @benjamin-es-hall, I remember this PR was meant as a way of fixing some animation glitch, but I guess it wasn't the best way to fix it. Anyway I removed that code and released version 2.8.4, please try and see if it works ok. Have a great day!

**Comment by benjamin-es-hall** [comment]
Oh wow thanks for the super quick update! I'll close this issue as now works as expected :) Thanks again!
