### ISSUE TITLE
Toast don't overlap toolBarItems when isOpaque = false

### ISSUE THREAD

**Issue by kHoLlSlCHeK** [exyte/PopupView#177]
Hello, dear developers! Please, help me with my problem 🥺

I have a ScrollView in ZStack and two toolBarItems (they are two button: left and right). If i use .isOpaque = true + .closeOnTap(true) or .closeOnTapOutside(true), toast overlap toolBarItems, but block UI current screen (i can't scroll or tap other UI elements), else i use .isOpaque = false + .closeOnTap(true), toast don't overlap toolBarItems and block UI current screen (i can scroll or tap other UI elements). I need that toast can overlap toolBarItems and don't block UI. How can i fix this case 🥺? Thanks in advance! 💖

**Comment by f3dm76** [comment]
Hey @kHoLlSlCHeK, the explanation for this is in "Show over navbar" section of readme. It is not possible because apple doesn't give any tools for that. Please let us know if you fins a workaround. Have a nice day
