### ISSUE TITLE
Improvement: Drag to dismiss

### ISSUE THREAD

**Issue by lrun-cmck** [exyte/PopupView#18]
Hi ! Thanks for your work and for sharing with us this library. I'm coming with a suggestion for improving the UX regarding the options that a user has in order to dismiss the popup. It would be cool if the user would be able to dismiss it by dragging down. Thanks a lot !

**Comment by f3dm76** [comment]
Hi @lrun-cmck , thank you for your kind words! Great suggestion, that would be really cool indeed, I'll work on it first time I get a chance. Have a great day!

**Comment by metrue** [comment]
Looking forward to this feature so much, I will take a look if I can do something,  you can drop any examples here if you have.

**Comment by f3dm76** [comment]
@lrun-cmck @metrue I'm happy to announce that a brand new version 0.0.13 contains long awaited drag to dismiss. You are most welcome to give it a go. Please let me know if's everything you were expecting from it. Have a wonderful day!

**Comment by metrue** [comment]
tried it, works like a charm.  thanks so much for your work @f3dm76

**Comment by metrue** [comment]
Hi, @f3dm76 

When I try the **drag to dismiss** feature, I found,
1. There's only one direction I can drag the popup view.
2. When I's trying to drag to other directions, the popup did not move, but it dismissed in the end. 
It maybe better we can drag to all the direction and dismiss I think, but still, it almost works perfectly. 

You can reproduce it in this [branch](https://github.com/exyte/PopupView/pull/27)

**Comment by f3dm76** [comment]
Hey @metrue , I fixed the issue with dismissing when dragging to other sides, please check out version 0.0.13. However, I don't think that dragging to both sides should work - definitely not for toasts and floaters, and arguably dragging even the simple popup both ways will create more chaos than convenience. Have a nice day.

**Comment by metrue** [comment]
Hi @f3dm76 just upgrading to 0.0.14, and yes, the dismissing when dragging to other sides issue fixed, thank you 😊 .
