### ISSUE TITLE
Popup breaks with autohide

### ISSUE THREAD

**Issue by MJegorovas** [exyte/PopupView#182]
```
import SwiftUI
import PopupView

struct ContentView: View {
    @State private var show = false
    var body: some View {
        VStack {
            Button("Popup") {
                show = true
            }
            Spacer()
        }
        .popup(isPresented: $show) {
            Text("POPUP")
        } customize: {
            $0.autohideIn(3).dismissCallback { print("DISMISS") }
        }
        .onChange(of: show) {
            print($0)
        }
    }
}
```

If you spam the button, something breaks and after few tries popup is no longer showed on the screen. Did not test this thoroughly, but I think issue lies when `show` property is set to `true` before `dismissCallback` is called.

**Comment by f3dm76** [comment]
Hey @MJegorovas, what version are you using? In current version `closingIsInProcess` is set to `true` - not `show`, please make sure you are using the latest version 2.9.1. I tested your code but it works stably even with constant spamming. Have a nice day

**Comment by MJegorovas** [comment]
Sorry, I don't really follow, but here's a video of the bug on 2.9.2 version with the code I posted above:

https://github.com/exyte/PopupView/assets/58346155/e8174e10-57d1-40f5-b80c-e590219fc592

The console output:
```
true
false
true
DISMISS
```

**Comment by f3dm76** [comment]
Hey @MJegorovas, thank you for providing details on how to reproduce, I was able to catch the issue. Please check out version 2.10.4, should be fixed there, have a wonderful day!
