### ISSUE TITLE
Readme is obsolete

### ISSUE THREAD

**Issue by kalil0321** [exyte/PopupView#185]
I was trying to run the app but the readme is obsolete. Is it possible to update it please.

**Comment by f3dm76** [comment]
Hey @kalil0321, please specify what exactly is obsolete? Also, there is a working example you can use to copy code from. Have a nice day

**Comment by kalil0321** [comment]
hi, 
thanks for your reply. I was talking about the path of the files: `cd <PopupViewRepo>/Example/`. This path doesn't exist no more and there are many others and I wasn't able to install the pod file. Anyway, I was able to download the dependency. It works really well. Amazing work. Thank you, have a nice day too.

**Comment by f3dm76** [comment]
@kalil0321, sorry, but this is the folder in your system to where you cloned the project - I could never guess its name and location, so this is just a general guideline - not an exact instruction

**Comment by kalil0321** [comment]
Thanks for your reply but I was referring to the /Example that I didn't find.
