### ISSUE TITLE
Dismiss drag doesn't work with NavigationStack

### ISSUE THREAD

**Issue by naughtont** [exyte/PopupView#186]
My popup contains only a NavigationStack. Dragging to dismiss doesn't work since the drag gesture is handled by the NavigationStack. As a workaround, I can put a view above the NavigationStack so the user can drag that to dismiss, or I could add a dismiss button.

It would be nice if dragging beyond a threshold in the NavigationStack would dismiss the popup.

**Comment by f3dm76** [comment]
Hey @naughtont, I don't think there is anything I can do if the drag gesture is handled by the NavigationStack - SwiftUI doesn't allow to detect touchDown and all these useful stuff. Can a `.scroll` popup type solve your issue by any chance? If no but you think that something can still be done, please attach your minimal compilable example code

**Comment by f3dm76** [comment]
It's been a while, so I'll close this one for now. Please feel free to reopen if you are still having the issue. Please be sure to attach minimal compilable reproducible example. Have a nice day!
