### ISSUE TITLE
Fix compilation error on visionOS

### ISSUE THREAD

**Issue by zuinqstudio** [exyte/PopupView#187]
Right now I'm not able to compile for visionOS even after opting out when platform is visionOS. I think this could address updating the Utils CGSize extension to return a zero size for visionOS:

```
extension CGSize {

    static var screenSize: CGSize {
#if os(iOS) || os(tvOS)
        return UIScreen.main.bounds.size
#elseif os(watchOS)
        return WKInterfaceDevice.current().screenBounds.size
#elseif os(macOS)
        return NSScreen.main?.frame.size ?? .zero
#elseif os(visionOS)
        return .zero
#endif
    }
}
```

**Comment by f3dm76** [comment]
Hey @zuinqstudio, thank you for your work. Did you launch example project on VisionOS with this code? Does it work as expected? Have a great day!

**Comment by zuinqstudio** [comment]
Thank you @f3dm76 for your quick response. Actually I didn't try yet so not sure if other problems will arise after fixing this one. I'll give it a try as soon as possible and will let you know.

**Comment by f3dm76** [comment]
i don't think other platforms will break, but if we are opting to support VisionOS - we'll have to guarantee that it works

**Comment by zuinqstudio** [comment]
Absolutely, I totally understand. Just manually imported the source code to try, and it actually works (I mean, no more compilation errors and I can run it again), so that would to it :)

**Comment by zuinqstudio** [comment]
By the way, I didn't expect it, but besides compiling & running, the PopUpView is actually working too :)

I don't know the potential side effects of returning incorrect size for `visionOS` but it seems to be working nicely.

<img width="735" alt="Captura de pantalla 2024-05-03 a las 12 15 46" src="https://github.com/exyte/PopupView/assets/750915/700312b9-6715-495b-820d-5a3d96eb86a4">

**Comment by f3dm76** [comment]
@zuinqstudio, popup uses screen size to calculate its position on screen and apply animations, it is very important for it to have the actual screen size to be able to guarantee its work in toast, floater and default modes, with opaque and non-opaque setting and etc. Is there a way to get the actual size of vision's "screen"?

**Comment by zuinqstudio** [comment]
Mm I see. Unfortunately, as far as I know the way to get screen size in vision is using a `GeomtryReader` from the root view. Something like this.-

```
var body: some View {
    GeometryReader { proxy in
        let windowSize = proxy.size
        ViewContent()
    }
}
```

so the easiest approach would be probably taking the size as a param on visionOS, would that make sense?

**Comment by f3dm76** [comment]
I guess so, yeah

**Comment by zuinqstudio** [comment]
@f3dm76, just wondering, any plans to add a patch for this at some point?

**Comment by f3dm76** [comment]
Hey @zuinqstudio, support for VisionOS is not in our plans yet, and we do not have free hands for the open source projects right now. However if you make a PR adding this functionality with actual screen size, launch the example project on VisionOS and test all popup types, and don't break any other OS support (I will help test otherOSs) - I will merge and release

**Comment by zuinqstudio** [comment]
I see, thank you for the clarifications!

**Comment by mschinis** [comment]
Hi, I have the same issue, and can't build for visionOS. I wouldn't mind helping to get this fixed.

**Comment by zuinqstudio** [comment]
@f3dm76 @mschinis Finally I had the time to download and try the test project on `visionOS`. Don't ask me how but returning a zero size on this target (as suggested previously) just works as seen in the linked video (very cool demo by the way!).-

https://www.dropbox.com/s/ygg1kim7ui15rx5/Grabaci%C3%B3n%20de%20pantalla%202024-06-02%20a%20las%2023.39.36.mov?dl=0

I'm happy to do a PR if you are okay with it.

**Comment by mschinis** [comment]
hey @zuinqstudio that looks great. I'll try out your solution on my vision pro and report back

**Comment by f3dm76** [comment]
Sure @zuinqstudio, let's do it, thanks for finding time to test! @mschinis it would be great if you can check it out too, please do report back, thank you. Have a great day, both if you!

**Comment by mschinis** [comment]
I can confirm this works with visionOS after a couple of tests with my app. Attaching a screenshot showing the popup in my app.

![IMG_0027](https://github.com/exyte/PopupView/assets/771903/0ec40e31-34b4-49d8-bb83-599ac9af4294)

Attaching elements while in immersive space however, does not work, since the RealityView coordinate space is completely different and would require ripping out and re-working the entire plugin.

For reference, [here's an example](https://gist.github.com/ynagatomo/9e89c0ca9bf1c408b05ded887e852920) of how something like this would be implemented for immersive view. 

That being said, I think implementing the above solution for now, would be the best approach to unblock the usage of this plugin in most apps.

**Comment by zuinqstudio** [comment]
@f3dm76 Seems I need permissions to push my branch in order to be able to PR. If granting permission is not an option and you have a chance to add the fix, the only thing I changed is the `visionOS` else branch in the `CGSize` extension.-

```
extension CGSize {

    static var screenSize: CGSize {
#if os(iOS) || os(tvOS)
        return UIScreen.main.bounds.size
#elseif os(watchOS)
        return WKInterfaceDevice.current().screenBounds.size
#elseif os(macOS)
        return NSScreen.main?.frame.size ?? .zero
#elseif os(visionOS)
        return .zero
#endif
    }
}
```

**Comment by mschinis** [comment]
@zuinqstudio You can fork the project, make your changes and create a Pull Request. 🙂

Happy to do that for you if you need help with it

**Comment by zuinqstudio** [comment]
Thank you for the tip @mschinis, not so familiarized with Github, I think I did it :)

**Comment by mschinis** [comment]
@f3dm76 I believe this can closed now?
