### ISSUE TITLE
 the view blinked after ios 16.3 was turned off

### ISSUE THREAD

**Issue by wscqs** [exyte/PopupView#188]
.position(.top)
//.isOpaque(true) // When I use isOpaque(true), the view blinked after ios 16.3 was turned off, but not later than ios 16.7

**Comment by f3dm76** [comment]
Sorry @wscqs I didn't understand your sentence. What do you mean "ios 16.3 was turned off"? Do you mean there is an issue on ios 16.3 but not on ios 16.7? In any case, please attach a minimal compilable example and make sure the issue reproduces on this minimal example, a video of the issue, and specify your xcode and ios versions. Have a nice day

**Comment by wscqs** [comment]
https://github.com/exyte/PopupView/assets/13110076/b315c541-8e60-44de-ba03-1139626eea5d

**Comment by wscqs** [comment]
here is an issue on ios 16.3 but not on ios 16.7

**Comment by f3dm76** [comment]
@wscqs Unfortunately, usually we only choose to support the latest major versions of the iOS and not have minor version specific fixes, the code could turn into a mess in that case. Seems like it’s a bug in the exact version of the OS, since it works fine on iOS 15, 16.7 and 17
