### ISSUE TITLE
Incorrect Operation of isOpaque Parameter in iOS 14 Bottom Sheet

### ISSUE THREAD

**Issue by azamattajiyev** [exyte/PopupView#190]
A problem with the isOpaque parameter for the bottom sheet on iOS 14 has been discovered. Setting isOpaque to true does not lead to the expected outcome — the window remains translucent.

**Steps to Reproduce:**

1. Create a bottom sheet in an application on iOS 14.
2. Set the isOpaque parameter to true.
3. Launch the application and open the bottom sheet.

**Expected Result:**
The popup is not visible.

```
.popup(isPresented: $isPresented) {
    Text("Hello, World")
} customize: {
    $0
        .type(.floater(verticalPadding: 0, horizontalPadding:0))
        .isOpaque(true)
        .position(.bottom)
        .closeOnTap(false)
        .closeOnTapOutside(true)
        .backgroundColor(.black.opacity(0.4))
        .dragToDismiss(true)
        .animation(.linear(duration: 0.15))
}
```

**Comment by f3dm76** [comment]
Hey @azamattajiyev, unfortunately we do not support ios 14, too many features do not work there
