### ISSUE TITLE
Can you add a type in middle zoom from small to big?

### ISSUE THREAD

**Issue by VolleyZ** [exyte/PopupView#193]
Can you add a type in middle zoom from small to big? 
and add a disappearToPosition method?

**Comment by f3dm76** [comment]
Hey @VolleyZ, good ideas both, please check out version 3.0.0 - both parameters are there, here is how to use them:
```
$0
          .type(.floater())
          .disappearTo(.centerScale)
```
Please mind the renaming: .top -> .topSlide to accommodate for new .scale case. Have a great day!
