### ISSUE TITLE
The popup not response tap gesture on iOS 16 device.

### ISSUE THREAD

**Issue by MainasuK** [exyte/PopupView#196]
After upgrade to v2.10.4. The popup view can not be tap anymore. Only pan gesture response for scrolling. 

The implementation likes this:

```
        .popup(isPresented: $viewModel.isShowingSelectChannelPopup, view: {
            ComposeChannelPickerView(viewModel: viewModel)
        }, customize: {
            $0
                .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                .position(.bottom)
                .isOpaque(true)
                .dragToDismiss(true)
                .closeOnTap(false)
                .animation(.spring())
                .closeOnTapOutside(true)
                .backgroundColor(Colors.black.swiftUIColor.opacity(0.2))
                .useKeyboardSafeArea(true)
                .dismissCallback {
                    viewModel.isPop = false
                }
        })
```

We rollback to v2.10.3 and issue gone.

**Comment by f3dm76** [comment]
Hey @MainasuK, thank you for reporting, however I tried the case you described, and I see no issues: 
https://github.com/exyte/PopupView/assets/9447630/19f1c04b-4455-4226-ba5a-21614efe64f8
Please attach a minimal **compilable** example and make sure the issue reproduces on this minimal example. Have a nice day

**Comment by MainasuK** [comment]
@f3dm76  Sorry. It may be misleading to mention the iOS version.

I'm using the Xcode 15.4 (15F31d) and built the example codes without any changes for the iOS 17.5 simulator. 

https://github.com/exyte/PopupView/assets/7940186/71903264-6023-48f7-bf81-175b2fd15ffd

**Comment by f3dm76** [comment]
They are not buttons, it's just an example

**Comment by MainasuK** [comment]
@f3dm76 It's my mistake to assert it's some buttons so I used the demo to verify the issue. Maybe the iOS version is still relative. Because the problem does not happen on iOS 17 devices.

And I can not reproduce the problem in a startup project. The code is not complicated enough so I guess some nested views raise this problem.

Thank you for your help. I just stay at v2.10.3 and it's working for me.

**Comment by f3dm76** [comment]
@MainasuK you don't have to provide the code from example project though - just please attach a compilable piece of your own code if you manage to extract it - in any case - have a wonderful day!
