### ISSUE TITLE
Example action sheet 2 not working

### ISSUE THREAD

**Issue by feelingsonice** [exyte/PopupView#197]
![IMG_E9B4974C498B-1](https://github.com/exyte/PopupView/assets/42384776/f2289d8f-0613-435c-88e9-e27a9be06542)

Example Action Sheet 2 not working for me.

Xcode 16 beta, iOS 18 Beta2

**Comment by f3dm76** [comment]
Hey @feelingsonice, thank you for reporting this, however this example is a .scroll popup demonstration, which uses [SwiftUIIntrospect](https://github.com/siteline/swiftui-introspect), which doesn't support ios 18 for now( Other than that I added ios 18 support in version 3.0.1, and will fix this example as soon as SwiftUIIntrospect is updated. Have a great day!

**Comment by f3dm76** [comment]
Please check out version 3.0.4, and be sure to have a great day!
