### ISSUE TITLE
Show popup on any screen in app

### ISSUE THREAD

**Issue by kk143g** [exyte/PopupView#199]
How to show popup on any screen in app.
**My Scenario**: Need to inform user about file download success. User could be on any screen.

**Comment by jeonghi** [comment]
To display a `popup` on any screen in an app, various design approaches can be used, and it depends on the developer's preference.

A popup view internally displays using a `@Binding` variable.
Therefore, to trigger a `popup` from a parent view, you need to declare a `@State` variable in the parent view and manage the state.

Deciding which view is responsible for state management is up to the developer.

**Comment by jeonghi** [comment]
> How to show popup on any screen in app. **My Scenario**: Need to inform user about file download success. User could be on any screen.

To display a `popup` on any screen in an app, various design approaches can be used, and it depends on the developer's preference.

A popup view internally displays using a `@Binding` variable.
Therefore, to trigger a `popup` from a parent view, you need to declare a `@State` variable in the parent view and manage the state.

Deciding which view is responsible for state management is up to the developer.

**Comment by f3dm76** [comment]
Hey @kk143g, @jeonghi's answer is absolutely correct - it is entirely up to you. You can attach a .popup is AppView for example and control its visibility and text with an environmental or static variable. Same as with `SwiftUI` sheet - it is the developer's responsibility. Have a nice day
