### ISSUE TITLE
not working in ios16

### ISSUE THREAD

**Issue by CoderGFWu** [exyte/PopupView#200]
https://github.com/exyte/PopupView/assets/17979026/02844f95-928a-4c4e-8afc-5966a9cac3bc

**Comment by f3dm76** [comment]
Hey @CoderGFWu, thank you very much for bringing this to our attention, please check out version 3.0.3 - have a brilliant day!

**Comment by Sunrizzin** [comment]
Same in 3.0.3

**Comment by f3dm76** [comment]
Feel free to reopen if the fix didn't work
