### ISSUE TITLE
[Small bug] Re-centering Popup on device rotation

### ISSUE THREAD

**Issue by BredBurr** [exyte/PopupView#202]
Hi creators of the best Popup library!

I've noticed a tiny bug:
In the latest release if you open the middle popup (better do it on the iPad) and rotate the device - the popup doesn't adjust to the center of the screen.

The 2.x.x on the contrary works flawlessly.
Best of luck!

**Comment by f3dm76** [comment]
Hey @BredBurr, thank you so much for bringing this to our attention and for your kind words. I'll be sure to take a look as soon as I have a minute, have a wonderful day!

**Comment by f3dm76** [comment]
Hey @BredBurr, please check out version 3.0.5, have a great day!
