### ISSUE TITLE
Bug when scroll 

### ISSUE THREAD

**Issue by ekamalov** [exyte/PopupView#216]
iOS 18, Xcode 16
when scrolling scrollView from bottom to top, the whole all content moves. 
![ScreenRecording_09-27-202411-15-14_1-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/a2edf0e3-2924-499a-8ceb-7aad002bedd5)

vs
![4](https://github.com/user-attachments/assets/736c34ff-c577-48b5-9d51-19d7c14cbd46)

**Comment by ekamalov** [comment]
There are also the following errors
<img width="2274" alt="image" src="https://github.com/user-attachments/assets/ab3e85d4-fb22-4844-af37-900c642fa19b">
<img width="1999" alt="image" src="https://github.com/user-attachments/assets/0b70e6a1-ea1a-45fa-a405-d5abcc52bad8">
<img width="2123" alt="image" src="https://github.com/user-attachments/assets/31d6c49d-cf0d-4f8a-a11d-ea4169ef5319">

**Comment by kobeisgod** [comment]
I encountered the same bug. When using ScrollView, scrolling down causes the entire popover to be hidden. This issue does not occur in iOS 16 or iOS 17.

**Comment by ekamalov** [comment]
@kobeisgod look #222
