### ISSUE TITLE
SourcePackages/checkouts/PopupView/Sources/PopupView/Modifiers.swift:11:16 Static property 'defaultValue' is not concurrency-safe because non-'Sendable' type '(() -> Void)?' may have shared mutable state

### ISSUE THREAD

**Issue by wlxo0401** [exyte/PopupView#217]
I am using version 3.1.1 and I just copied the example, but the above error occurred.
I'm using Xcode 16.0.

**Comment by uniqby** [comment]
+1

**Comment by ekamalov** [comment]
+1

**Comment by alexantonica** [comment]
**Fast and temporary workaround** 
Set the library to this git hash `c82f68dd56d9359e144ab0446f5866208e4a02e8` 
It's the last merge commit before the commit that forces the library to use swift 6 
I had the same errors and it build ok now. But don't forget to keep an eye here for when they solve/revert so you cna put back the `master` branch 🙏

**Comment by kwikysw** [comment]
same. this project got totally abandoned

**Comment by elriando** [comment]
same for me

**Comment by elriando** [comment]
> **Fast and temporary workaround** Set the library to this git hash `c82f68dd56d9359e144ab0446f5866208e4a02e8` It's the last merge commit before the commit that forces the library to use swift 6 I had the same errors and it build ok now. But don't forget to keep an eye here for when they solve/revert so you cna put back the `master` branch 🙏

work but, now got error "Type 'PlatformViewVersion<iOSVersion, ScrollViewType, UIScrollView>' has no member 'v18'",  


#if os(iOS)
        switch type {
        case .scroll(let headerView):
            VStack(spacing: 0) {
                headerView
                    .fixedSize(horizontal: false, vertical: true)
                ScrollView {
                    view()
                }
                // no heigher than its contents
                .frame(maxHeight: scrollViewContentHeight)
            }
            .introspect(.scrollView, on: .iOS(.v15, .v16, .v17, .v18)) { scrollView in
                configure(scrollView: scrollView)
            }
            .offset(CGSize(width: 0, height: scrollViewOffset.height))

        default:
            view()
        }
#else

**Comment by asifbilal786** [comment]
same for me

**Comment by f3dm76** [comment]
Hey guys, please check out version 3.1.2. Unfortunately we do not have resources for open source projects right now, please keep in mind that you can always commit PRs to speed things up. Have a nice day
