### ISSUE TITLE
quickly tap outside before popupview appear cause crash

### ISSUE THREAD

**Issue by AlfinIndrawan** [exyte/PopupView#219]
this crash happen in simulator and real device

here is my code

.popup(isPresented: $isPopUpPresented) {
      EditPopupView(itemID: $itemId, isPopUpPresented: $isPopUpPresented)
    } customize: { $0
      .type(.default)
      .appearFrom(.bottomSlide)
      .closeOnTap(false)
      .dragToDismiss(false)
      .closeOnTapOutside(true)
      .backgroundColor(Color.glass)
    }
    
    popupview version i use 3.1.2
    
https://github.com/user-attachments/assets/2c14f19b-efe1-4002-b5e5-90c103cc89e0

**Comment by foxman2** [comment]
#220 fixed, please update and try again

**Comment by AlfinIndrawan** [comment]
Yup fixed. Thanks
