### ISSUE TITLE
Prevent the tap event bubbling

### ISSUE THREAD

**Issue by metrue** [exyte/PopupView#24]
Hi, Thanks for your works on this cool project, I have question that when we enable `closeOnTapOutside` ,  how can enable prevent the outside view object receiving the tap event?

**Comment by f3dm76** [comment]
Hey @metrue, I think you can add .`disabled(popupPresented)` to the outside content. I could add a flag, but it looks more like a job for the user, than for a popup library - not hte library's place to decide what's happens with its context. Have great day!

**Comment by metrue** [comment]
`disabled` is nice solution enough, thanks @f3dm76
