### ISSUE TITLE
Keep getting "Invalid frame dimension" error 

### ISSUE THREAD

**Issue by metrue** [exyte/PopupView#25]
When dismissing the popup view, got error message often, anyone know how to resolve it?

```
2021-04-14 12:51:35.864282+0800 gikiapp[923:160335] [SwiftUI] Invalid frame dimension (negative or non-finite).
2021-04-14 12:51:35.883202+0800 gikiapp[923:160335] [SwiftUI] Invalid frame dimension (negative or non-finite).
```

**Comment by f3dm76** [comment]
Hey @metrue, sorry for the slow answer. I don't see any errors in example project output. Could you please provide your example if that is still happening to you and you are sure the problem is not on your end. Have a great day!

**Comment by metrue** [comment]
Just tried to reproduce it again and found that the root cause is I use a `TextEditor` as the content view of `popup`,  but did not set the frame correctly.
```Swift
  .frame(width: .infinity, height: 200)
```
Replace it following fix the issue.
```Swift
  .frame(width: UIScreen.main.bounds.width, height: 200)
```

**Comment by karimuddin-tech** [comment]
am getting same error 
` .frame(width: UIScreen.main.bounds.width, height: CGFloat(269), alignment: .top)`

any other solution please

**Comment by karimuddin-tech** [comment]
`ZStack{
                Image("blue-bottom-round")
                    .resizable()
                    .frame(width: UIScreen.main.bounds.width, height: CGFloat(269), alignment: .top)
                VStack(alignment: .center, spacing: nil, content: {
                    Image("logo-white")
                        .resizable()
                        .scaledToFit()
                        .frame(width: 178, height: 138)
                })
            }`

**Comment by f3dm76** [comment]
Hey @karimuddin-tech, would you please provide a minimal but complete and reproducible example for me, so I can look into that?

**Comment by niloriver** [comment]
Why the debugger can't provide the source of the error ? 
Apple is boring.

**Comment by f3dm76** [comment]
Sometimes it does show runtime errors here, with a violet triangle:
<img width="89" alt="Image" src="https://github.com/user-attachments/assets/c62d8332-cb2a-4598-9a0f-932b994b287f" />
