### ISSUE TITLE
Limitation usage

### ISSUE THREAD

**Issue by golangnext** [exyte/PopupView#3]
PopouView `.popup` requires a host view to be a fullscreen. For example, if I put `.popup` at a view with height =200, it will show a different way.
Is there any better way to allow it to attach to any view and show at the correct position?

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-21 at 10 02 13](https://user-images.githubusercontent.com/47587402/82509121-58ec7c80-9b4a-11ea-9422-bef456c1e1fd.png)

**Comment by f3dm76** [comment]
Hey @golangnext , thanks for your report, I do believe you are right. Please check out new 0.0.2 version, should work there.

**Comment by golangnext** [comment]
I tried the 0.0.2, that's amazing :)
