### ISSUE TITLE
closeOnTapOutside causes issues with SegmentedPicker

### ISSUE THREAD

**Issue by feodormak** [exyte/PopupView#36]
Hi,
I have found that if the view being presented by `PopupView` contains a `SegmentedPicker` view and `closeOnTapOutside` is `true`, the `SegmentedPicker` does not respond to changes with the usual tap gesture, only to long presses and dragging of segments across it. I believe there are issues with the `TapGesture` responsible for `closeOnTapOutside`.

Example with `closeOnTapOutside` set to `true`
https://user-images.githubusercontent.com/17231825/127427851-838b4b1c-99ce-490a-9085-29199ddb0b19.mov

Example with `closeOnTapOutside` set to `false`

https://user-images.githubusercontent.com/17231825/127427950-4720fbf1-ad75-4301-bd0c-cf24efce5eb8.mov

**Comment by manindaniil** [comment]
Hey @feodormak !
Thank you so much for reporting this issue!
We’ve checked the issue and noticed the following things:
If you set the arguments in popup view

```
closeOnTap: false, closeOnTapOutside: false - all the works as expected 
closeOnTap: false, closeOnTapOutside: true - all the works as expected

closeOnTap: true,  closeOnTapOutside: true - picker’s tap is broken as in your video
closeOnTap: true,  closeOnTapOutside: false  - picker’s tap is broken as in your video
(because closeOnTap handle all simple taps from popup view)
```

Try to set the `closeOnTap` field as `false` then your case tap will work as you want. 

If it does not resolve your issue, please, provide us your code. 
Have a nice day!

**Comment by f3dm76** [comment]
Hey @feodormak, I'm closing this one since it's been a while. Please let us know if you are still having issues with this. Have a nice day!
