### ISSUE TITLE
How to dim background when show popup?

### ISSUE THREAD

**Issue by long-nguyen** [exyte/PopupView#37]

**Comment by JetForMe** [comment]
I have this need, too.

**Comment by manindaniil** [comment]
Hey @long-nguyen  !
Thank you so much for reporting this issue !
We added the ability to set a color of background area, just set `backgroundColor` in the Popup modifier, by default - Color.clear. 
Have a nice day !

**Comment by f3dm76** [comment]
Hey @long-nguyen, I'm happy to announce that this feature was included in 1.0.2 release and is now live! Have a wonderful day!
