### ISSUE TITLE
Position .center?

### ISSUE THREAD

**Issue by JetForMe** [exyte/PopupView#38]
Hi there. Thanks for this library. Could we also get a position .center? Thanks!

**Comment by f3dm76** [comment]
Hey @JetForMe, sorry for the late answer, would you please elaborate: for which popup type do you need this? Default popup type is already in the center, and center position for toasts doesn't really make sense to me. Have a good day.

**Comment by f3dm76** [comment]
Hey @JetForMe, I'm closing this one since it's been awhile. Please don't hesitate to reopen and share your thought on center alignment. Have a nice day!
