### ISSUE TITLE
Environment property for popup to dismiss itself?

### ISSUE THREAD

**Issue by JetForMe** [exyte/PopupView#39]
Is there a way for the popup to dismiss itself when it doesn't have access to the presentation state variable? Something like `self.presentationMode.wrappedValue.dismiss()`?

**Comment by manindaniil** [comment]
Hey @JetForMe !

We discussed this feature and resolved that we won't add environment property to the Popup View.
Technically, we can add @Environment key for dismissing a Popup, and it works. But only for one Popup entity. From SwiftUI's side, it cannot handle more than one entity of one key. 
Therefore if we can add environment dismiss() action we cannot guarantee the correct work of the action if users use a few Popups.

You can try to implement this functionality for your specific case.
And if you can run it for any number of Popups, we will be glad to your PR.

Have a nice day !
