### ISSUE TITLE
Close Modal When Click to Outside

### ISSUE THREAD

**Issue by halilyuce** [exyte/PopupView#4]
Hello, thanks for this useful pod :) 

I recommend if you add a feature for hiding modal when users click to the outside of modals, it will be so useful :)

Thanks in advance.

**Comment by f3dm76** [comment]
Hello @halilyuce , thank you for your kind words) Sounds like a good idea. I'll try implementing that and will let you know if/when it's ready. Have a great day!

**Comment by halilyuce** [comment]
@f3dm76 you're welcome :) Thanks for reply, have a great day 🙋🏻‍♂️

**Comment by f3dm76** [comment]
Hello once again @halilyuce , I added new closeOnTapOutside parameter in 0.0.3 version, which you are most welcome to try. Have a good one)

**Comment by halilyuce** [comment]
Thank you so much 👏🙌 I'm testing it immediately :)
