### ISSUE TITLE
Evaluate Popup view after invocation

### ISSUE THREAD

**Issue by JetForMe** [exyte/PopupView#40]
Is it possible to defer invoking the view closure until after the popup state changes and needs to be displayed?

**Comment by f3dm76** [comment]
Hey @JetForMe, we deferred initial popup's body creation till the first actual presentation, but it is not being deallocated after that, like system sheets do. Hope that fits your needs. The fix is included in 1.0.2 release which is now live, please give it a go. Have a marvellous day!

**Comment by f3dm76** [comment]
Hey @JetForMe, hope we satisfied your need of lazy content - I'll close the issue, but please let us know if it wasn't enough. Have a wonderful day)
