### ISSUE TITLE
Is there a way to make the toast show on top of modals?

### ISSUE THREAD

**Issue by bratxdy** [exyte/PopupView#47]
Ideally we'd like to be able to display a toast and it appear no matter if there was a modal on the screen or not. Right now if there is a modal the toast appears underneath it. We could add the view modifier onto this modal view, but then the toast would go down once the view was dismissed. Is this something that is possible?

**Comment by f3dm76** [comment]
Hey @bratxdy, that's an interesting question. I'm sorry to say right now we are short on time, but we will look into that when we have time. Thank you for reaching out, have a great day!

**Comment by manindaniil** [comment]
Hey @bratxdy !
I'm not sure that it is possible in the SwiftUI right now.
There are a few ways to implement this functional
- change your hierarchy and add a `.popup` modifier to the top view. 
- change a way presentation of modal views.

At the moment, in SwiftUI, such views as e.g. `.sheet` and some other views will be added to the top of `WindowGroup`, which causes problems for creating a universal solution.

If you find a solution lets us know !

Have a nice day !

**Comment by skywalkerlw** [comment]
I have the same problem/concern on it

**Comment by f3dm76** [comment]
@bratxdy, @skywalkerlw, hey, I added the ability to display popups on top of each other and on top of sheets also. Now you can chain popups - they will use their presenting view's dimensions for their position calculations - not the whole screen like they used to. If anything doesn't work right, please do share your examples with me. Hope that'll help both of you, have a wonderful day!

**Comment by f3dm76** [comment]
It's been a while so I'm closing this one for now, please do let me know if you have any further issues. Have a good day!
