### ISSUE TITLE
autoHide might be failed in Xcode 13

### ISSUE THREAD

**Issue by TerryHuangHD** [exyte/PopupView#48]
# Description
* autohideIn is not working: the dismissCallback will be called continuously, and the dialog is not dismissed

```
.popup(isPresented: $viewModel.infoToastShow,
                       type: .floater(verticalPadding: 15),
                       position: .top,
                       autohideIn: 2,
                       dismissCallback: viewModel.infoToastCallback) {
                           // UI
                       }
```

# Xcode
![Screen Shot 2021-10-06 at 11 38 15 PM](https://user-images.githubusercontent.com/574599/136237135-45302beb-3dd7-4ed7-9584-ebca81d0023d.png)

**Comment by manindaniil** [comment]
Hey @TerryHuangHD !
I've checked your issue, and `autohideIn` and `dismissCallback` are working correctly, at the least in Examples. Also, I've checked with simple `ViewModel: ObservableObject` in Xcode 13A233, it is working too. 

Maybe you have a problem with reinit of your ViewModel ? 
You can provide us with more detailed information and we will help to solve the problem.

**Comment by TerryHuangHD** [comment]
It seems to be interfered with other @Published properties in the same view model. 
I changed the design and it works now.
Thanks for helping out.
