### ISSUE TITLE
Popup view should be lazy loaded

### ISSUE THREAD

**Issue by ghost** [exyte/PopupView#5]
Here is an example

The current implemention is even `showSystemAlertNotification` = false, popup body is still executed. This could bring some problems in reality: 

`data` struct is set a valid value only if showSystemAlertNotification= true. Since it's not lazy-loaded, a crash happens since self.systemAlertNotification = nil

```swift
.popup(isPresented: $showSystemAlertNotification, type: .floater(), position: .top, animation: Animation.spring()) {
                SystemAlert(alert: self.data!)
            }
```

**Comment by f3dm76** [comment]
Hello @golangnext , that's a really good suggestion. However, we are using viewModifier, and the standard lazy view approach doesn't seem to be working here. We are still searching for a solution, but if you have any ideas, fill free to create a pull request.

**Comment by golangnext** [comment]
lazy view is a potential solution?

```
struct LazyView<Content: View>: View {
    let build: () -> Content
    init(_ build: @autoclosure @escaping () -> Content) {
        self.build = build
    }

    var body: Content {
        build()
    }
}
```

**Comment by f3dm76** [comment]
Yes, that's what I wrote: "we are using viewModifier, and the standard lazy view approach doesn't seem to be working here" :)

**Comment by golangnext** [comment]
I'm thinking maybe we can use a conditional modifier for that, like

```swift
extension View {
    typealias ContentTransform<Content: View> = (Self) -> Content
    @ViewBuilder func conditionalModifier<TrueContent: View, FalseContent: View>(
        _ condition: Bool,
        ifTrue: ContentTransform<TrueContent>,
        ifFalse: ContentTransform<FalseContent>
    ) -> some View {
        if condition {
            ifTrue(self)
        } else {
            ifFalse(self)
        }
    }
}
```

**Comment by f3dm76** [comment]
In the last WWDC video about lazy HStack and VStack, Apple specifically notes that you should avoid using lazy unless absolutely necessary. So I think we are not going to make it lazy by default for now. But if you want it to be lazy you can always wrap it in lazy modifiers on your end. Have a great day!
