### ISSUE TITLE
how to pass custom Text to pop up

### ISSUE THREAD

**Issue by beks6** [exyte/PopupView#54]
Hey all, I have Button which calls a ScannerView and receives the scanned barcode. I would like to pass the scanned String to a popup view and can't figure out how to do it properly. The pop up is always empty

That's my simplified code

```
struct WorkflowView: View {

    @State private var isShowingScanner = false
    @State private var scannedCode: String?
    @State private var isShowingScannerBanner = false

    var body: some View {
        ZStack{ //need to trigger pop up views
            VStack {
                    Button(action: {
                        self.isShowingScanner = true
                    }, label: {
                        Text("Scan barcode")
                            .font(.title)
                            .padding(5)
                            .background(Color.orange)
                            .cornerRadius(10)
                    })
            }
            .sheet(isPresented: $isShowingScanner) {
                    CodeScannerView(codeTypes: [.ean8, .ean13, .upce, .code39, .code93, .code128, .code39Mod43, .interleaved2of5, .qr]) { response in
                        if case let .success(result) = response {
                            scannedCode = result.string
                            isShowingScanner = false
                            isShowingScannerBanner = true
                        }
                    }
                }
        }
        .popup(isPresented: $isShowingScannerBanner, type: .floater(verticalPadding: 90), position: .top, autohideIn: 2) {
                    createSuccessBanner(message: scannedCode ?? "")
                }
}
```

**Comment by f3dm76** [comment]
Hello @beks6, your code doesn't show if your CodeScannerView works and actually updates scannedCode value. Also doesn't show how createSuccessBanner works - might be losing your value there. But if both of them work as expected, the code basically looks something like this: 
```
struct ContentView: View {

    @State private var scannedCode: String?
    @State private var isShowingScannerBanner = false

    var body: some View {
            VStack {
                Button {
                    self.scannedCode = "\(Double.random(in: 0...100))"
                    isShowingScannerBanner = true
                } label: {
                    Text("Scan barcode")
                        .font(.title)
                        .padding(5)
                        .background(Color.orange)
                        .cornerRadius(10)
                }
            }
        .popup(isPresented: $isShowingScannerBanner, type: .floater(verticalPadding: 90), position: .top, autohideIn: 2) {
            Text("\(scannedCode ?? "")")
        }
    }
}
```
This code updates content successfully, please check it out. If you have any further questions please provide minimal reproducible example. Also please make sure you are using the latest versions of xcode, ios and popup library. Have a nice day!

**Comment by Mxsella** [comment]
> Hello @beks6, your code doesn't show if your CodeScannerView works and actually updates scannedCode value. Also doesn't show how createSuccessBanner works - might be losing your value there. But if both of them work as expected, the code basically looks something like this:
> 
> ```
> struct ContentView: View {
> 
>     @State private var scannedCode: String?
>     @State private var isShowingScannerBanner = false
> 
>     var body: some View {
>             VStack {
>                 Button {
>                     self.scannedCode = "\(Double.random(in: 0...100))"
>                     isShowingScannerBanner = true
>                 } label: {
>                     Text("Scan barcode")
>                         .font(.title)
>                         .padding(5)
>                         .background(Color.orange)
>                         .cornerRadius(10)
>                 }
>             }
>         .popup(isPresented: $isShowingScannerBanner, type: .floater(verticalPadding: 90), position: .top, autohideIn: 2) {
>             Text("\(scannedCode ?? "")")
>         }
>     }
> }
> ```
> 
> This code updates content successfully, please check it out. If you have any further questions please provide minimal reproducible example. Also please make sure you are using the latest versions of xcode, ios and popup library. Have a nice day!

The problem here is that if I pass the custom text in this way, pop will display the previous value. Each click displays the value before the change.

**Comment by antonioreyna** [comment]
hello i have a similar issue,

```
@State private var loadingTitle: String? = nil
    @State private var loadingMessage: String? = nil
```

then on a button click i do:

```
self.loadingTitle = "title"
self.loadingMessage = "message."
showLoading = true
```

And mi popup looks like this but the texts are empty, just the "ok" fixed one appears.

```
.popup(isPresented: $showLoading) {
                VStack {
                    //Text("ok")
                    Text("\(loadingTitle ?? "")")
                        //.frame(maxWidth: .infinity)
                    //Text("\(loadingMessage ?? "")")
                }
                .padding(20)
                .background(Color.white)
                .cornerRadius(4)
                .shadow(color: .black.opacity(0.2), radius: 4, x: 0, y: 1)
                .padding(20)
            } customize: {
                $0
                    .animation(.spring())
                    .closeOnTap(false)
                    .closeOnTapOutside(false)
                    .dragToDismiss(false)
                    .isOpaque(true)
                    .backgroundColor(.white.opacity(0.5))
            }
```
