### ISSUE TITLE
Toast popup is not displayed when using sheet on ipad.

### ISSUE THREAD

**Issue by sheat-git** [exyte/PopupView#57]
The default popup is displayed, so it may be that the toast exists further down than the ipad's sheet display area.

Xcode 13.2.1
iPadOS 15.2

**Comment by f3dm76** [comment]
![simulator_screenshot_B8248E9C-79F0-47C8-9487-454C6F094080](https://user-images.githubusercontent.com/9447630/152956364-3f6aa4ab-82bc-46dc-bb7e-de013a20361b.png)
Hey @sheat-git, tried launching on iPad, seems to work alright. Used the same setup. Could you please provide more details about your problem?

**Comment by sheat-git** [comment]
This happens only in the view in the .sheet.
You can reproduce it by rewriting ExampleApp.swift as follows.

```swift
import SwiftUI

@main
struct ExampleApp: App {
    var body: some Scene {
        WindowGroup {
            ShowSheetView()
        }
    }
}

struct ShowSheetView: View {
    @State private var showSheet = false
    var body: some View {
        Button("show sheet") {
            showSheet = true
        }
        .sheet(isPresented: $showSheet) {
            ContentView()
        }
    }
}
```

**Comment by f3dm76** [comment]
Hey @sheat-git, I added the ability to display popups on top of each other and on top of sheets also. Now you can chain popups - they will use their presenting view's dimensions for their position calculations - not the whole screen like they used to. If anything doesn't work right, please do share your examples with me. Hope that helps, have a wonderful day!

**Comment by sheat-git** [comment]
thank you sooo much!!
