### ISSUE TITLE
how to transparent background Colour for bottom sheet popup?

### ISSUE THREAD

**Issue by naveedmcs** [exyte/PopupView#59]
![Screenshot 2022-03-10 at 2 39 55 PM](https://user-images.githubusercontent.com/21976150/157634704-eef9ac08-35a5-4c8b-867a-a2fed34b443c.png)

**Comment by naveedmcs** [comment]
![Screenshot 2022-03-10 at 2 39 55 PM](https://user-images.githubusercontent.com/21976150/157634634-bf414b5e-0b82-45ee-b3ca-555c444f273a.png)

**Comment by naveedmcs** [comment]
Please check my screenshot for example

**Comment by f3dm76** [comment]
If you meant semi-transparent black bg - I assume it is controlled by backgroundColor parameter in popup modifier. But I can't tell where exactly it's coming from since I haven't seen your code. Please provide your code and better description of your problem
