### ISSUE TITLE
Top Floater is showing a line after dismissed

### ISSUE THREAD

**Issue by yashvyas29** [exyte/PopupView#60]
I just cloned the repository and tried the example but it seems top floater is leaving a line after it gets dismissed.
All other popup types doesn't show it.

<img src=https://user-images.githubusercontent.com/5429210/161053880-604a98ba-8b93-42af-a6ec-8548cb8e7d28.png width=360>

I am using Xcode 13.3.
In between thanks for making this great library.

**Comment by f3dm76** [comment]
Hey @yashvyas29, thank you for your kind words. However, I launched the example (also Xcode 13.3, iOS 15.4, tested on sim iPhone 13 max pro, and on device iPhone mini 12), and everything works as expected. I tried dismissing by tap, drag and by timer - no lines. Do you maybe have some additional reproduction steps? Have a great day!

**Comment by yashvyas29** [comment]
I am using iPhone 13 mini simulator, iOS 15.4 on M1 mac. If that matters.
Getting the top floater bottom line every time after dismiss using auto, tap or drag.
It disappears when we launch any other toast or floater. But not when we launch Popup or Card.

Note: I tried it for iPod Touch - 7th generation simulator and its not appearing there.

**Comment by f3dm76** [comment]
https://developer.apple.com/forums/thread/690570
Could this be that this sim is a bit broken?
