### ISSUE TITLE
Ignore NavigationBar in Popup

### ISSUE THREAD

**Issue by rifqifadh** [exyte/PopupView#61]
popup with background not ignore navigationview, is it possible to cover all screen while keep using navigationview ?

![Screen Shot 2022-04-01 at 16 06 29](https://user-images.githubusercontent.com/38750970/161232457-10851eea-1e3c-4b74-bf0a-cff0709fb75e.png)

**Comment by f3dm76** [comment]
Hey @rifqifadh, it doesn't seem to be possible to force any view to be shown above navbar view. Navbar just takes priority. What you can do is move your popup up your view hierarchy to be "above" your navigation view. Like this:

```
NavigationView {
            ...
        }
        .popup(isPresented: $showingTopToast, backgroundColor: .black.opacity(0.5)) {
            Color.red.frame(width: 50, height: 50)
        }
```

**Comment by f3dm76** [comment]
It's been a while so I'm closing this one for now, please do let me know if you have any further issues. Have a good day!

**Comment by f3dm76** [comment]
Hey @rifqifadh, I think I found a solution using Apple's `fullScreenCover`, please check it out:

```
extension View {

    func transparentFullScreenCover<Content: View>(isPresented: Binding<Bool>, content: @escaping () -> Content) -> some View {
        fullScreenCover(isPresented: isPresented) {
            ZStack {
                content()
            }
            .background(TransparentBackground())
        }
    }
}

struct TransparentBackground: UIViewRepresentable {

    func makeUIView(context: Context) -> UIView {
        let view = UIView()
        DispatchQueue.main.async {
            view.superview?.superview?.backgroundColor = .clear
        }
        return view
    }

    func updateUIView(_ uiView: UIView, context: Context) {}
}
```

Use like this:
```
        .transparentFullScreenCover(isPresented: $viewModel.isPresentedSettings) {
            Color.black.opacity(0.5).edgesIgnoringSafeArea(.all)
                .popup(isPresented: $viewModel.isPresentedSettings, type: .toast, position: .bottom) {
                    DraggableCardView() {
                        SettingsView(viewModel: ProfileViewModel())
                    }
                }
        }
```

Sorry if I'm a bit late, have a great day!

**Comment by owen12ab** [comment]
Is there any way to achieve this without using fullScreenCover?

**Comment by JoeOCT91** [comment]
Is any way to pass user interaction when using fullScreenCover,
is it possible to manage that by presenting a new UI Window above the current window
@f3dm76

**Comment by f3dm76** [comment]
Hey @JoeOCT91, this is a pure SwiftUI library though. If using UIKit is acceptable for your project, then please use one of the number of great UIKit popup libraries

**Comment by f3dm76** [comment]
@JoeOCT91 Why are you tagging me?
