### ISSUE TITLE
PopupView stays visible when running 'Designed for iPad' on macOS

### ISSUE THREAD

**Issue by swilson** [exyte/PopupView#62]
If set to show on the bottom the view moves up the screen when dismissed. Tried increasing the hiddenOffset to no avail. https://drive.google.com/file/d/1w3eB-60w5Ua6J-ulJKLbeGxRyFhEJYpG/view?usp=sharing

**Comment by f3dm76** [comment]
Hey @swilson, I'm sorry to say we do not support mac catalyst, so I removed the target completely, sorry for not doing it in the first place. You could use mac target if you need to run on macOS. Have a good day!
