### ISSUE TITLE
add default value for floater's vertical padding

### ISSUE THREAD

**Issue by murad1981** [exyte/PopupView#63]
When I use the type `.floater(verticalPadding:)` in case of a `NavigationView` and the position is `top`, the popup view appears on top of the notch in iPhone X and later, which requires me to calculate `safeAreaInsets.top` and then add it to the padding, this can be done using `GeometryReader` which's not suitable in some situations and has side effects.
I believe adding a default value for the padding to include top safe area insets would be a good idea.

**Comment by f3dm76** [comment]
Hey @murad1981, added another parameter to floater enum: useSafeAreaInset. If true - safe area is added to verticalPadding value. Please check out version 1.1.0. Have a great day! 

P.S. To get safe area without changing your layout just use GeometryReader in .background:

```
struct FrameGetter: ViewModifier {

    @Binding var frame: CGRect
    @Binding var safeArea: EdgeInsets

    func body(content: Content) -> some View {
        content
            .background(
                GeometryReader { proxy -> AnyView in
                    let rect = proxy.frame(in: .global)
                    // This avoids an infinite layout loop
                    if rect.integral != self.frame.integral {
                        DispatchQueue.main.async {
                            self.safeArea = proxy.safeAreaInsets
                            self.frame = rect
                        }
                    }
                    return AnyView(EmptyView())
                }
            )
    }
}
```

**Comment by murad1981** [comment]
I tried the version on tag `1.1.0` and it works perfectly and even in `.sheet` Views too, thank you for your support and many thanks for the `FrameGetter` modifier, I needed it in many cases but I found myself stumbled upon finding the right way to calculate `safeAreaInsets` without engaging myself with `UIKit`
