### ISSUE TITLE
"floater" popup type appears momentarily after dismissing the keyboard

### ISSUE THREAD

**Issue by murad1981** [exyte/PopupView#67]
I have the following simple setup for my top floater popup, it appears without problems when the binding var toggles to true, but I noticed a UI bug in which the floater appears for a very short moment after finish editing in a `TextField` - you can copy and paste the code snippet to try it out:

```
struct ContentView: View {
    @State var text = ""
    @State var showPopup = false
    
    var body: some View {
        NavigationView {
            VStack {
                TextField("enter text", text: $text)
                Button {
                    showPopup = true
                } label: {
                    Text("Show the popup")
                }
            }
        }
        .popup(isPresented: $showPopup,
               type: .floater(),
               position: .top,
               autohideIn: 2) {
            HStack {
                Text("Test Message")
            }
            .frame(maxWidth: .infinity)
            .padding()
            .background(Color.red)
        }
    }
}
```

following is a video screenshot for the bug:

https://user-images.githubusercontent.com/1199045/169879370-56b39599-cdd5-4895-ba4d-942a13b2d2ab.mov

**Comment by f3dm76** [comment]
Hey @murad1981, great catch - thank you for bringing this into our attention, we'll take a look as soon as we can. Have a great day!
