### ISSUE TITLE
Animation is lost while the popup is being dismissed

### ISSUE THREAD

**Issue by murad1981** [exyte/PopupView#69]
The `easeInOut` animation of the floater `popUp` will be lost if the `popUp` has been presented using the `item...` function, like in this snippet:

```
struct ContentView: View {
    @State var message: String?
    
    var body: some View {
        
        NavigationView {
            
            Button {
                message = "this is a test message"
            } label: {
                Text("Show the popup")
            }
        }
        .popup(item: $message,
               type: .floater(),
               position: .top,
               autohideIn: 2) { _ in
            HStack {
                Text("Test Message")
            }
            .frame(maxWidth: .infinity)
            .padding()
            .background(Color.red)
        }
    }
}
```

this will not happen if we present the `popUp` using `isPresented....` function.

video screenshot:

https://user-images.githubusercontent.com/1199045/173104043-6e3f0d29-eda7-4bef-bfb7-ab926623d58e.mov

**Comment by f3dm76** [comment]
Hey @murad1981, fixed the issue by reverting changes to item popup variant. Now I do not return item in closure, just like it used to be before. Have a great day!

**Comment by murad1981** [comment]
that solve the issue .. thank you @f3dm76
