### ISSUE TITLE
popup not showing correctly

### ISSUE THREAD

**Issue by toseefkhilji** [exyte/PopupView#72]
Hi ,

I am working on app, to show toast message using below code.

But issue is If once Popup toast show, second time it's not showing.

```
struct ContentView2: View {
    @State var showingPopup = false

    var body: some View {
        ZStack {
            Color.yellow
            VStack {
                Button("Show Popup", action: {
                    showingPopup = true
                })
            }
        }
        .popup(isPresented: $showingPopup, type: .toast, position: .bottom, autohideIn: 2) {
            Text("The popup")
                .frame(width: 200, height: 60)
                .background(Color(red: 0.85, green: 0.8, blue: 0.95))
                .cornerRadius(30.0)
        }
    }
}
```

https://user-images.githubusercontent.com/2367614/181250056-eb963e2b-00dc-46e5-a2aa-d037ed12b9f3.mov

M I doing something wrong?
How can is show different toast messages in same view?

**Comment by f3dm76** [comment]
Hey @toseefkhilji, the code you attached works perfectly well. Please make sure you have the latest version and provide more details about your xcode version etc. if the problem reproduces for you on this code. Have a nice day

**Comment by toseefkhilji** [comment]
Thanks for update. Please find below detail.

Xcode **Version 13.4.1**
pod **ExytePopupView version 1.1.5**
Apple **Macmini M1 - macOS 12.3.1**

I'm still facing issue, popup is not working as per expectation. like .top and .bottom is coming to middle.
Expected result is it should stick to top or bottom not in middle.


https://user-images.githubusercontent.com/2367614/181426537-1c3655f0-fddf-40e3-a113-69e3bb3e296b.mov



Please find attached sample project.
[TestPopup.zip](https://github.com/exyte/PopupView/files/9205581/TestPopup.zip)

**Comment by f3dm76** [comment]
@toseefkhilji could you also please attach ios version and what simulator/device you are using

**Comment by f3dm76** [comment]
Ah, I see in the video

**Comment by toseefkhilji** [comment]
@f3dm76 : Did you get chance to see issue?

**Comment by toseefkhilji** [comment]
@f3dm76 : Did you get chance to see issue?

**Comment by f3dm76** [comment]
@toseefkhilji Your first code does not reproduce. In your second you are attaching the popup to a view which is not fullscreen, so it is showing on top of THAT view, calculating popup's location using THAT view's size. Have a nice day

![simulator_screenshot_E419CE5F-2B39-4545-A3D8-B47A338A5B0A](https://user-images.githubusercontent.com/9447630/183348039-6c9b057f-f6e8-41fb-9b40-513ec72ee4b8.png)

**Comment by toseefkhilji** [comment]
@f3dm76 : thanks for explaination.
