### ISSUE TITLE
Popup height issue in case of TextView used in View

### ISSUE THREAD

**Issue by khawarappsgenii** [exyte/PopupView#75]
Am facing popup height issue in case of TextView used in View which we have passed. The popup covers whole screen height instead of jus adjusted to the height based on view content. 
May be something wrong with TextView.

**Comment by f3dm76** [comment]
Hey @khawarappsgenii, could you please provide a minimal reproducible example?

**Comment by f3dm76** [comment]
It's been a while, so I'll close this one for now. Please feel free to reopen if you are still having the issue.

**Comment by akardas16** [comment]
this issue is still presenting. I will open new issue with some details
