### ISSUE TITLE
about show toast at modals

### ISSUE THREAD

**Issue by programmerchan** [exyte/PopupView#77]
hello
i am using your toast but some problem with me can you help me?
iam register toast in view A, when i use 'navigationLink'  to view B, B use 'navigationLink' to view C,view B and C can show toast as well
but when i use 'fullscreenCovert' or 'sheet' to show view B, toast not shown in view B,it will stil shown in view A
Is there a way to make the toast show on top of modals(register toast once)?
thanks
have a nice day

**Comment by f3dm76** [comment]
Hello @programmerchan, sorry but no, Apple doesn't give me enough right for that. Popup is just an overlay, it can't be shown above anything but the view itself
