### ISSUE TITLE
Fatal error: UIViewRepresentables must be value types: SignInWithApple

### ISSUE THREAD

**Issue by Ian8829** [exyte/PopupView#78]
When I upgrade my XCode version to 14 this error is occured. (tested with ios16 simulator)

My ExytePopupView package version is 1.1.6.

Why is this error happened?

![Screen Shot 2022-09-22 at 3 30 59 PM](https://user-images.githubusercontent.com/23634595/191674475-b9d4d933-d0b5-4ade-b961-b7f1bb0caf54.png)
![Screen Shot 2022-09-22 at 3 31 12 PM](https://user-images.githubusercontent.com/23634595/191674508-de8d13ed-9645-42b2-a667-05b61ee0804d.png)

**Comment by f3dm76** [comment]
@Ian8829, looks like your 'SignInWithApple' is declared as a 'class', while swiftUI expects it to be a 'struct', could you please try changing that? Have a nice day
