### ISSUE TITLE
App crashes using sheet (with button press)

### ISSUE THREAD

**Issue by d-morgan** [exyte/PopupView#79]
App crashes randomly and intermittently when Popup triggered by button press. I'm using a very similar approach to the 4th example in the README (the sheet).

`AttributeGraph precondition failure: setting value during update`

It seems like the `proxy.safeAreaInsets` isn't available randomly

![Screenshot 2022-09-27 at 18 46 36](https://user-images.githubusercontent.com/1569839/192599406-537a9d98-1cfe-4eca-a946-68fb5ac0cbef.png)

**Comment by f3dm76** [comment]
Hey @d-morgan, I reimplemented this one using UIApplication to get safe area, hope that solves your issue. Please check out version 1.2.0. Have a marvellous day!

**Comment by EProgressPro** [comment]
Hey @f3dm76 

Problem:
In my case, FrameGetter both crash in 1.2.0 and earlier version(iOS15 & iOS16).

Log:
iOS16: AttributeGraph precondition failure: setting value during update
iOS15: precondition failure: deleting updating attribute

Solution:
I added delay before async updating value, and It works for me in most cases.
Hope that helps.

```
// I'm using version 1.1.x
struct FrameGetter: ViewModifier {
    
    @Binding var frame: CGRect
    @Binding var safeArea: EdgeInsets
    
    func body(content: Content) -> some View {
        content
            .background(
                GeometryReader { proxy -> AnyView in
                    let rect = proxy.frame(in: .global)
                    // This avoids an infinite layout loop
                    if rect.integral != self.frame.integral {


//                        DispatchQueue.main.async {
//                            self.safeArea = proxy.safeAreaInsets
//                            self.frame = rect
//                        }


                        // ⬇️
                        DispatchQueue.global(qos: .userInitiated).asyncAfter(deadline: .now() + 0.1) {
                            DispatchQueue.main.async {
                                self.safeArea = proxy.safeAreaInsets
                                self.frame = rect
                            }
                        }


                    }
                    return AnyView(EmptyView())
                }
            )
    }
}
```

**Comment by bcho** [comment]
I am still seeing this error in v2.8.4 . This happens when the sheet view needs to be recreated or presented before the pop up view being updated (dismissed for example). It seems in this case, accessing the GeometryProxy will cause app crash.

I am using a workaround similar to above, but to delay the sheet open after a short duration.
