### ISSUE TITLE
Xcode 12 build failure

### ISSUE THREAD

**Issue by golangnext** [exyte/PopupView#8]
I can see this error in new XCode 12

`The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions`

![image](https://user-images.githubusercontent.com/47587402/85338382-89e31700-b525-11ea-9211-e5799bae35fd.png)

**Comment by f3dm76** [comment]
Hello @golangnext, fixed the issue, please check out version 0.0.6, have an even greater day!
