### ISSUE TITLE
Popup from bottom does not cover navigation bar

### ISSUE THREAD

**Issue by jtressle** [exyte/PopupView#84]
Hi,

Great library! 

I'm trying to replace partialSheet with the bottom popupview from this library, but I'm having trouble with the navigation bar.
The solution proposed here (https://github.com/exyte/PopupView/issues/61#issuecomment-1118347975) animates weird because you can see the transparent view come up from the bottom.  

How would one get the the same behavior as in the partial sheet library? The main reason I'm considering switching is because they do not support activity sheets for iPads.

https://github.com/AndreaMiotto/PartialSheet

Thanks,

**Comment by f3dm76** [comment]
Hey @jtressle I think I fixed that issue in 1.3.0, please check it out, have a nice day

**Comment by f3dm76** [comment]
@jtressle In version 2.0.0, please use .isOpaque(true) to get truly fullscreen popup, have a nice day

**Comment by jtressle** [comment]
@f3dm76 perfect thank you.  I'll test this shortly.
