### ISSUE TITLE
How to make width of popup to all screen?

### ISSUE THREAD

**Issue by azaitsev** [exyte/PopupView#85]
Hello,

firstly, thank you for amazing lib!

I'm trying to implement a pop up and make it all screen width. I've tried `.frame(maxWidth: .infinity)` but it doesn't help.

Maybe you can share some cool design of popups (like you used in screenshot on readme page)?

**Comment by f3dm76** [comment]
Hey @azaitsev thank you for your kind words, all the popups examples are in example project, please check them out. Please feel free to share you code if you won't be able to make it work after all. Have a beautiful day!

**Comment by f3dm76** [comment]
Please don't hesitate to reopen if you have more questions
