### ISSUE TITLE
'fullScreenCover(isPresented:onDismiss:content:)' is only available in iOS 14.0 or newer

### ISSUE THREAD

**Issue by st-small** [exyte/PopupView#87]
I have project with minimal iOS 16 version. After adding the dependency through SPM, got error in the Utils.swift file.
<img width="1184" alt="Снимок экрана 2022-12-29 в 12 33 46" src="https://user-images.githubusercontent.com/1850189/209939162-0d6efedf-2f1a-4c16-9da0-c65be82c041d.png">

How to fix this problem?

**Comment by f3dm76** [comment]
Hey @st-small, please check out version 1.3.0, should be fixed there, have a great day!

**Comment by gaetano78** [comment]
Same error, I have 1.3.0 version
