### ISSUE TITLE
Cannot find 'FullscreenPopup' in scope

### ISSUE THREAD

**Issue by uniqby** [exyte/PopupView#88]
After updating to 1.3
**Cannot find 'FullscreenPopup' in scope**

<img width="1524" alt="Screenshot 2022-12-29 at 17 07 20" src="https://user-images.githubusercontent.com/1488394/209979367-24cf36a3-a841-4ebc-95d0-b227152a2f49.png">

**Comment by f3dm76** [comment]
Hey @uniqby I was in the process of updating it then, sorry, should be alright now, please check it out, have a great day!

**Comment by f3dm76** [comment]
Please don't hesitate to reopen if the issue persists
