### ISSUE TITLE
Popup blocks touch propagation to List View

### ISSUE THREAD

**Issue by SlayterDev** [exyte/PopupView#9]
When using this library with a List and Navigation links, you have to hold the list cell to activate the navigation link or swipe to delete.

Here is the code I'm using to set up the toast:

```swift
.popup(isPresented: $showCopiedToast,
                   type: .toast,
                   position: .bottom,
                   autohideIn: 2,
                   closeOnTap: false) {
                HStack {
                    Text(self.toastText)
                }
                .frame(width: 200, height: 60)
                .background(Color(red: 0.85, green: 0.8, blue: 0.95))
                .cornerRadius(30.0)
                .padding(15)
            }
```

My guess is the `simultaneousGesture` stuff is messing with the list view. A workaround or fix would be appreciated.

**Comment by SlayterDev** [comment]
Further Info: Reverting to 0.0.4 fixes my issue but the toast is not displayed.

Running on Xcode 12 Beta 1, iOS 14

**Comment by Vercisor** [comment]
Having the same problem here. No workaround found yet.

**Comment by f3dm76** [comment]
@SlayterDev I used your attached code, but the issue does not reproduce. Could you please attach a piece of code reproducing the issue? I guess I could just remove the touchOutside stuff, but people specifically asked me to add it, I hope I can find a way to fix this without removing it, once I'm able to reproduce your problem.

**Comment by SlayterDev** [comment]
I’ll try to add a more complete example today. Is it possible to put that functionality behind a default parameter so it can be turned off if desired?

**Comment by SlayterDev** [comment]
Can confirm @Vercisor's fix. I forked the library and removed the `simultaneousGesture` parts as a quick dirty fix. Placing these behind an optional parameter would at least be a fix for this situation.

**Comment by f3dm76** [comment]
@SlayterDev @Vercisor Pushed my workaround, please check it out - version 0.0.7

**Comment by SlayterDev** [comment]
Looks good. Thank you.
