### ISSUE TITLE
There are the following errors in 1.3.0

### ISSUE THREAD

**Issue by hnher** [exyte/PopupView#91]
'onChange(of:perform:)' is only available in iOS 14.0 or newer

My iOS version is required to be above 15.0

I downgrade PopupView to 1.2.1

**Comment by f3dm76** [comment]
Hey @hnher thank you for bringing this to my attention, please check out version 1.3.1m should be resolved there, have a beautiful day!

**Comment by f3dm76** [comment]
Please don't hesitate to reopen if the issue persists
