### ISSUE TITLE
text with binding is not showing full text

### ISSUE THREAD

**Issue by akardas16** [exyte/PopupView#92]
when using binding property in view Text is not showing completely. it just shows a few of sentence.
<img width="311" alt="Screenshot at Jan 16 16-57-05" src="https://user-images.githubusercontent.com/28716129/212720439-2e90801a-1311-4007-ad66-c897d30f145a.png">

**Comment by f3dm76** [comment]
Hey @akardas16, please attach a minimal reproducible compilable code sample, so I can help you. Have a nice day

**Comment by f3dm76** [comment]
It's been a while so I'm closing this one, please fill free to attach an example and reopen if you still have a problem
