### ISSUE TITLE
Popup from bottom does not always animate in the correct direction

### ISSUE THREAD

**Issue by jtressle** [exyte/PopupView#93]
Hi,

I just updated to version 2.0.0, and I'm having issues with the following popup animating correctly.

`
                .popup(isPresented: $showingMenu, view: {
                    menu()
                }, customize: {
                    $0
                        .type(.toast)
                        .position(.bottom)
                        .closeOnTap(true)
                        .closeOnTapOutside(true)
                        .backgroundColor(.black.opacity(0.4))
                })
`

I'm toggling `showingMenu` from a navigation button, and have placed the above code onto a ZStack.  

The first time I click my button, the menu animates correctly from the bottom.  All subsequent button presses have the menu animating from the top down.  This was not occurring in version 1.3.

Again, many thanks for this library.  

Thanks,

**Comment by jtressle** [comment]
Just an update:

I just switched phones, and updated to 16.2 from 16.1.  It looks like this issue also is on version 1.3.  What I found is that `displayedOffset` is being called twice when presenting from the bottom in my code.  The reason I'm getting an animation from that top is that `presenterContentRect` is all zeros.  I'll investigate further, but I think the popup struct is being initialized twice?

**Comment by jtressle** [comment]
Closing this for now because I think my main view is causing this issue.  I'll report back any findings.

**Comment by jtressle** [comment]
I'm reopening this issue, but I still don't have a concrete reason why the bottom toast fails to animate correctly on my app, but not on the example app.  

My view hierarchy is basically:

`
ZStack {
  NavigationView {
    Color.white
            .edgesIgnoringSafeArea(.bottom)
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .principal) {
                    Image("icon")
                        .colorMultiply(Color.primary)
                        .padding()
                }
            .navigationBarItems(
                leading:
                    Button(action:{ [weak viewModel] in
                          self.actionSheets.show1 = true
                    }) {
                        Image(systemName: "")
                    }
                    .buttonStyle(PlainButtonStyle())
                , trailing:
                        Button  {
                            self.actionSheets.show2 = true
                        } label: {
                            Image("")
                        }
            )
            }
  }
}
        .popup(isPresented: $actionSheets.show1, type: .toast, position: .bottom, closeOnTap: true, closeOnTapOutside: true, backgroundColor: .black.opacity(0.4), view: {
            actionSheet1()
        })
        .popup(isPresented: $actionSheets.show2, type: .toast, position: .bottom, closeOnTap: true, closeOnTapOutside: true, backgroundColor: .black.opacity(0.4), view: {
            actionSheet2()
        })
`

Both 1.3.1 and 2.0.0 have the same issue.  It's also interesting that actionSheet2() is more prone to animating wrong.  Also, sorry if the example above has syntax errors.  It's just a high-level example.

Thanks

**Comment by f3dm76** [comment]
Hey @jtressle since it works as expected in the example app, I cannot really help you unless you provide a compilable minimal reproducible example. Could you please attach such an example? Have a nice day

**Comment by jtressle** [comment]
Hi @f3dm76, I was able to reproduce the issue with this example.  In the iOS example app, replace line 14 `ContentView()` with `ContentViewExample()`.  On my device, clicking on "First" will animate the `ActionSheetFirst` from the top down. I've also attached a video showing the issue.  

My device is running 16.2.  

Hope this helps.

Thanks. 

https://user-images.githubusercontent.com/13778165/213796898-037e1bc4-9cfc-436d-ba6f-f08c290d374d.mp4

[ContentViewExample.swift.txt](https://github.com/exyte/PopupView/files/10469920/ContentViewExample.swift.txt)

**Comment by Rittenzore** [comment]
same issue!

**Comment by yujinqiu** [comment]
same issue!

**Comment by Dave181295** [comment]
Same issue friends

**Comment by pomeloL** [comment]
Same issue friends

**Comment by pomeloL** [comment]
same issue!！！！！！

**Comment by pomeloL** [comment]
same issue!！！！！！！

**Comment by f3dm76** [comment]
Hey everyone, thank you for your reports, sorry it took me a while, but please check out version 2.1.3, the issue should be gone there. Special thanks to @Rittenzore for figuring out the exact root of this issue, it helped me a lot in fixing it. Have a wonderful day guys!

**Comment by Dave181295** [comment]
@f3dm76  Hey, when updating to 2.1.3 and running I got a crash 
![Capture d’écran 2023-05-16 à 22 31 52](https://github.com/exyte/PopupView/assets/76634618/57aeec91-f3c2-45e1-8857-c8a2f153c2b9)

This is the usage: 

```
.popup(item: $showPopup) { item in

customize: {
            $0
                .type(.toast)
                .position(.bottom)
                .animation(.easeInOut)
                .dragToDismiss(true)
                .closeOnTapOutside(true)
                .dismissCallback {
                    shouldBlurView = false
                }
      
        }
```

**Comment by Dave181295** [comment]
**Update**

Just had to init it as nil instead

`@State private var showPopup:PopupType?
`
instead of 

`@State private var showPopup:PopupType  = .interests
`

Still a bug tho

**Comment by f3dm76** [comment]
Hey @Dave181295, I don't get it, where is the body of popup in your example? And you are missing a {. Could you please attach a compilable example? Also, would you please create another ticket, since what you are facing is another issue.
