### ISSUE TITLE
Call Popup from objc

### ISSUE THREAD

**Issue by ilia1103** [exyte/PopupView#95]
Hi, I have been programming in swift quite recently, can you help me? I don't use SwiftUI when building screens, how can I call your popup from the objc function?
<img width="835" alt="Снимок экрана 2023-01-26 в 10 58 55" src="https://user-images.githubusercontent.com/80444674/214784698-dab8777f-a7ad-493f-bc24-c88cd735a7cc.png">

I copied your popups into the project into separate classes, the question remains, how do I call them on the screen)

**Comment by f3dm76** [comment]
Hello @ilia1103, I'd suggest you use a UIKit native solution for UIKit project, like this one https://github.com/huri000/SwiftEntryKit. If you still prefer using this library please search for something like https://blog.logrocket.com/how-add-swiftui-uikit-project/. Have a nice day
